/**
 * Project content.
 *
 * IMAGES: the six screenshots below are placeholders generated into
 * `public/projects/`. Drop your real files into that folder and change the
 * paths here — that is the only edit needed (e.g. "/projects/carder.jpg").
 */
const img = {
  carder: "/projects/carder-hero.png",
  carderMedia: "/projects/carder-media.png",
  carderTiers: "/projects/carder-tiers.png",
  golegal: "/projects/golegal-editor.webp",
  muterpe: "/projects/muterpe.svg",
  alfa: "/projects/alfa.svg",
  volumize: "/projects/volumize.svg",
  wisdomup: "/projects/wisdomup.svg",
} as const;

export const projectImages = img;

export type Metric = { value: string; caption: string; note?: string };

/*
 * `image` is optional. Some of what a build is made of has no public screen to
 * show — an internal back office, a billing path — and captioning an unrelated
 * picture as that thing is worse than showing nothing. A block without an image
 * renders full width instead.
 */
export type BuildBlock = { title: string; body: string; image?: string; alt?: string };

export type Project = {
  slug: string;
  index: string;
  name: string;
  accentWord: string;
  tagline: string;
  summary: string;
  role: string;
  timeline: string;
  status: string;
  inDevelopment?: boolean;
  liveUrl?: string;
  liveLabel?: string;
  /** The URL is a login wall, not a public page. Say so before it is clicked. */
  liveGated?: boolean;
  stack: string[];
  indexMetrics: string[];
  image: string;
  alt: string;
  problem: string;
  problemHeadline: string;
  approach: string;
  decisions: string[];
  diagram?: { src: string; alt: string; caption: string };
  build: BuildBlock[];
  metrics: Metric[];
  /*
   * Where the numbers above came from, and what they are not.
   *
   * A percentage with no baseline and no method is one a reader discounts, and
   * every case study here carries several. This is the line that says which
   * are platform records, which are self-reported, and which are counts of
   * what exists rather than readings of what happened.
   */
  metricsNote?: string;
  /**
   * Per-project section headings.
   *
   * These default to one phrasing for all six, which was fine when two case
   * studies carried the format and became a template once all six did. A
   * rescue and a greenfield build should not have the same silhouette, so each
   * project can name its own sections.
   */
  headlines?: {
    constraints?: string;
    tradeoffs?: string;
    build?: string;
    result?: string;
  };
  reflection: string;

  /*
   * The three sections below are what separate an account of a job from a list
   * of tasks completed, and all three are optional so a case study can be
   * upgraded one at a time rather than all six at once.
   */

  /** Team, scale and ownership. What a reader needs before the problem means anything. */
  context?: { k: string; v: string }[];
  /**
   * What could not be done. A build with no stated constraints reads as a
   * greenfield exercise; naming them is what shows the work was real.
   */
  constraints?: { title: string; body: string }[];
  /**
   * Decisions written as decisions: what was chosen, what was rejected, what it
   * cost and what it bought. "Integrated Stripe" is a task. "Chose Stripe as
   * the source of truth over mirroring entitlements locally, and paid for it in
   * network calls" is a decision.
   */
  tradeoffs?: { decision: string; instead: string; cost: string; bought: string }[];
  /** Production failures, kept in the reader's view — the device mailagent already uses. */
  broke?: { title: string; body: string }[];
};

/*
 * The projects as written. The catalogue index is deliberately absent: it is
 * derived from ORDER below, so the number on the page and the number in the
 * counter cannot drift apart again.
 */
const authored: Omit<Project, "index">[] = [
  {
    slug: "carder",
    name: "Carder",
    accentWord: "Carder",
    tagline: "AI Mini-Site Builder",
    summary:
      "An AI mini-site builder for local businesses: one prompt becomes a complete site in about 30 seconds. I led the backend, data, billing and media infrastructure.",
    role: "Backend & Infrastructure Lead",
    timeline: "Nov 2022 – Feb 2026",
    status: "Live",
    liveUrl: "https://carder.app",
    liveLabel: "carder.app",
    stack: ["Laravel", "Next.js", "TypeScript", "Node.js", "Express", "SQL", "Stripe", "AWS S3"],
    /*
     * No revenue figure. The public pricing is $0 / $12 / $29 with a free tier
     * most sites sit on, so any MRR number stated here would be contradicted by
     * the pricing page one click away. Users and adoption are the two claims
     * that survive being checked.
     */
    indexMetrics: ["150+ users", "+40% adoption", "3 metered tiers"],
    image: img.carder,
    alt: "Three sites generated by Carder: a bakery menu, a salon services page, and an Arabic restaurant menu in right-to-left layout",
    problemHeadline: "A list of links is not a business",
    problem:
      "Small businesses often need more than a link list but cannot justify a custom site or learn a page builder. Carder generates the full business page from one sentence. The engineering challenge was adding reliable billing, usage metering and media delivery to a live Laravel product without disrupting paying customers.",
    context: [
      { k: "TEAM", v: "Two backend engineers working with product and frontend" },
      { k: "USERS", v: "150+ subscribers across the Middle East and Europe, live throughout" },
      { k: "OWNED", v: "Schema · billing · quotas · media · admin · CI/CD" },
      { k: "NOT MINE", v: "Generation models and the marketing site" },
      { k: "RUNTIMES", v: "Laravel core, Node/Express services for specific workloads" },
      {
        k: "PRODUCT",
        v: "Free · Pro $12/mo · Business $29/mo, metered at 5 / 10 / 30 AI generations a month",
      },
    ],
    constraints: [
      {
        title: "The product was live the whole time",
        body: "Every schema change had to support a running application and every deployment needed a rollback path that did not require restoring a backup.",
      },
      {
        title: "Laravel was not up for replacement",
        body: "The established Laravel core stayed in place. New services had to integrate with its database and workflows rather than justify a rewrite.",
      },
      {
        title: "A two-person backend team",
        body: "With no dedicated platform team, every new service also became ours to deploy, monitor and support.",
      },
    ],
    approach:
      "I kept Laravel as the core and isolated the workloads hurting it. Media moved to object storage, while billing and quota state were derived from their authoritative source. Every change was designed for a system that could not stop running.",
    decisions: [
      "Kept Laravel as the core while separating media and billing workloads.",
      "Derived entitlement from Stripe instead of trusting a local account flag.",
      "Metered AI generation by plan without locking existing sites when the quota ended.",
      "Built an admin back office that uses the product’s own billing paths.",
    ],
    tradeoffs: [
      {
        decision: "Stripe is the source of truth for entitlement",
        instead: "Mirror subscription state into our own tables and trust the local copy",
        cost: "Entitlement requires a provider call or a short-lived cache that must be invalidated correctly.",
        bought: "Refunds and failed renewals change access promptly, without a stale local copy granting the wrong tier.",
      },
      {
        decision: "Meter generations, not requests",
        instead: "Cap the expensive thing at the API layer, or trust the client not to ask twice",
        cost: "Monthly counters must handle resets, retries and partial failures correctly.",
        bought: "Plans limit the operation with a real unit cost while ordinary editing and browsing remain unrestricted.",
      },
      {
        decision: "A Node service for the media pipeline, Laravel for everything else",
        instead: "Handle uploads in Laravel like the rest of the application",
        cost: "A second runtime added deployment, monitoring and patching overhead.",
        bought: "Image uploads stopped competing with page requests for PHP workers.",
      },
      {
        decision: "Expand and contract for every schema change",
        instead: "Alter the column and ship it",
        cost: "Changes take multiple deploys while old and new shapes coexist.",
        bought: "Live migrations remain reversible without restoring a database backup.",
      },
      {
        decision: "Signed S3 URLs, delivered from the edge",
        instead: "Proxy the bytes through the application server",
        cost: "Expiring URLs and a signing endpoint add lifecycle and caching work.",
        bought: "The application no longer handles image bytes, and delivery scales independently at the edge.",
      },
    ],
    broke: [
      {
        title: "Entitlement drifted from billing",
        body: "The first version trusted locally mirrored subscription state. Duplicate, delayed and out-of-order Stripe webhooks let that copy drift from the billing record, sometimes granting the wrong access.",
      },
      {
        title: "The fix was to stop remembering",
        body: "Entitlement now comes from Stripe. Webhooks are idempotent by event ID, and stale events are discarded, so replaying an event is a no-op.",
      },
    ],
    diagram: {
      src: "/projects/carder-architecture.svg",
      alt: "Carder architecture: Laravel core with Node services for media, Stripe as the source of truth for entitlement, signed S3 delivery cached at the edge, and an admin back office writing through the same billing paths",
      caption: "* REQUEST, BILLING AND MEDIA PATHS",
    },
    build: [
      {
        title: "Media that never touches the app",
        body: "Uploads go directly to S3 through signed URLs and are delivered from the edge. The API never handles image bytes, so media growth does not consume request workers.",
        image: img.carderMedia,
        alt: "Photo-heavy generated sites: a photographer's portfolio, a bakery menu and a yoga studio schedule",
      },
      {
        title: "Three tiers, asked on every request",
        body: "Free, Pro and Business plans control pages, sites, domains and generation quotas. Entitlement is derived from Stripe and briefly cached for frequent checks on save, publish and domain lookup.",
        image: img.carderTiers,
        alt: "Sites of differing scope generated by Carder: a single-page studio site, a multi-page law firm site and a dental clinic site",
      },
      {
        title: "An admin panel over the whole tenancy",
        body: "The back office covers accounts, sites, companies and subscriptions without requiring production SQL. Changes flow through the same billing and entitlement paths as the product.",
        // No image, deliberately: the admin panel is internal and has no public
        // screen. Drop a redacted screenshot in here if one ever exists.
      },
      {
        title: "Metering the one expensive operation",
        body: "Monthly quotas apply only to AI generation: 5 on Free, 10 on Pro and 30 on Business. Existing sites stay editable, and failed generations do not consume allowance.",
        // No image: generation quota is a billing rule, not a screen. The
        // pricing page states the numbers; nothing shows the meter itself.
      },
    ],
    metrics: [
      { value: "150+", caption: "Users, ME & Europe", note: "* two regions, as of Feb 2026" },
      { value: "+40%", caption: "Adoption growth", note: "* after relaunch, to Feb 2026" },
      { value: "3", caption: "Metered tiers", note: "* free · $12 · $29, 5 / 10 / 30 generations" },
      { value: "0", caption: "Downtime migrations", note: "* expand / contract, against live data" },
    ],
    headlines: {
      constraints: "What a live product would not let us do",
      tradeoffs: "What each choice cost",
      build: "What Carder is made of",
      result: "What Carder measured",
    },
    metricsNote:
      "User count and tier structure come from platform records and public pricing. The +40% compares the first instrumented month with February 2026, not the full rebuild. Zero-downtime migrations counts schema changes shipped against live data, not uptime.",
    reflection:
      "I’d instrument adoption from day one. Early features shipped on intuition, so the +40% improvement only became visible after analytics arrived.",
  },
  {
    slug: "golegal",
    name: "Golegal",
    accentWord: "Golegal",
    tagline: "AI Legal Workspace",
    summary:
      "A consumer legal platform for drafting, review, signing, obligation tracking and access to regulated solicitors. I built five modules end to end.",
    role: "Full-Stack & AI Engineer — five modules, end to end",
    timeline: "Dec 2024 – Jan 2026",
    status: "Live",
    liveUrl: "https://go-legal.ai",
    liveLabel: "go-legal.ai",
    stack: ["Nest.js", "Next.js", "PostgreSQL", "OpenAI", "Agentic RAG", "React Flow", "Plate.js"],
    indexMetrics: ["95% accuracy", "-30% manual work", "50+ users"],
    image: img.golegal,
    alt: "The Go Legal AI document editor: a confidentiality agreement open with track changes, beside the Copilot review panel showing traffic-light analysis, a document health score and the individual clause findings behind it",
    problemHeadline: "Generic chat can’t be trusted with legal text",
    problem:
      "Legal teams lose hours to reading, extracting, and reformatting the same document types. Generic LLM chat wasn’t accurate enough to trust with legal text — it hallucinated citations and lost document context.",
    context: [
      {
        k: "OWNED",
        v: "Five modules end to end: document creation and RAG · e-signature and obligation extraction · legal pathways · tasks, calendar and notes · the services marketplace",
      },
      { k: "ALSO BUILT", v: "Payments and the token-metered usage module the paid plans run on" },
      {
        k: "NOT MINE",
        v: "The legal content and the regulated advice — Go Legal Ai is not a law firm, and the services are delivered by independent regulated firms",
      },
      { k: "PRODUCT", v: "Free · Power Up £19/mo · Pro £49/mo, metered in AI credits per action" },
      { k: "REACH", v: "England & Wales for instructed services; document generation across 150+ jurisdictions" },
    ],
    constraints: [
      {
        title: "Plausible is not good enough",
        body: "A fluent but incorrect clause can create legal risk. The system had to ground claims in the user’s document and jurisdiction, making retrieval quality more important than a larger prompt.",
      },
      {
        title: "Every AI action costs real money",
        body: "Drafting, review and extraction cost per call and are sold as credits. Accuracy improvements had to justify their effect on unit economics.",
      },
      {
        title: "The legal steps cannot be skipped, only made lighter",
        body: "Drafting, review, signing and obligation tracking have real dependencies. The interface could simplify the sequence but not remove its controls.",
      },
    ],
    approach:
      "The solution combined structure-preserving retrieval with document-specific extraction agents. Around that pipeline, I added credit metering and a single working surface for a legal flow a non-lawyer could complete.",
    tradeoffs: [
      {
        decision: "Sell AI work as credits, priced per action",
        instead: "One flat unlimited subscription, the way most SaaS is sold",
        cost: "Customers must understand credits, and plan pages must explain each action’s price.",
        bought: "Usage stays tied to model cost, protecting margins without making light users subsidize heavy ones.",
      },
      {
        decision: "Tune retrieval for precision, not coverage",
        instead: "Retrieve generously and let the model decide what is relevant",
        cost: "Chunking and routing require more work, and an occasional relevant passage may not surface.",
        bought: "Fewer confident but misleading answers, the more dangerous failure in legal text.",
      },
      {
        decision: "One working surface for drafting, review and signing",
        instead: "A wizard with a page per step, which is easier to build and easier to reason about",
        cost: "One screen carries more state and requires stricter component boundaries.",
        bought: "Users remain in the document instead of crossing multiple abandonment points.",
      },
    ],
    decisions: [
      "Chunked documents by clause hierarchy so retrieved passages retain their context.",
      "Routed document types to dedicated agents with focused tools and validation schemas.",
      "Modelled legal matters as pathway graphs of drafts, AI steps, services and court forms.",
      "Extracted dated obligations from signed documents into the user’s calendar.",
    ],
    diagram: {
      src: "/projects/golegal-rag.svg",
      alt: "Golegal agentic RAG pipeline: documents chunked along their own clause hierarchy so each chunk keeps its ancestry, embedded into PostgreSQL, retrieved with that context intact, then routed by a classifier to a per-document-type agent with its own tools and validation schema",
      caption: "* RETRIEVAL THAT KEEPS THE DOCUMENT SHAPE",
    },
    build: [
      {
        title: "Retrieval that keeps the document’s shape",
        body: "Documents are chunked by section, clause and sub-clause, with ancestry attached to every chunk. Retrieved passages keep their meaning and no longer require the model to infer missing context.",
      },
      {
        title: "One agent per document type",
        body: "A classifier routes contracts, filings and correspondence to dedicated extraction agents. Each path has its own tools and validation schema for the fields that document type should contain.",
      },
      {
        title: "Legal pathways, as a graph you can see",
        body: "React Flow models each legal matter as ordered actions, from drafting and waiting periods to AI steps, services and court forms. Users can see the current step and its dependencies.",
        image: "/projects/golegal-pathways.png",
        alt: "The Legal Pathway builder: a React Flow canvas with a Start node branching into an action, a smart template, an asset-tracing service, an AI step and a court form, connected by dependency edges",
      },
      {
        title: "Signature, and what the signature commits you to",
        body: "After multi-party signing, the platform extracts notice periods, renewal windows and payment deadlines from the executed document so commitments remain actionable.",
        image: "/projects/golegal-signature.png",
        alt: "A fully signed document in Go Legal AI showing both signers with timestamps, alongside the Extract obligations action and the signing certificate",
      },
      {
        title: "The deadlines the documents created",
        body: "Extracted obligations become calendar entries with tasks, notes and reminders. The dashboard leads with overdue and upcoming work.",
        image: "/projects/golegal-tasks.png",
        alt: "The Tasks and Deadlines module: a calendar view with counters for upcoming deadlines, pending and overdue tasks, and reminders, plus notes and integrations tabs",
      },
      {
        title: "When the AI is not enough, order a person",
        body: "A priced services catalogue lets users order regulated legal work when AI is insufficient. Fees include VAT, jurisdiction is explicit and the platform clearly states that it is not a law firm.",
        image: "/projects/golegal-services.png",
        alt: "The Legal Services catalogue: fifteen priced services across consultation, contracts, disputes, document services, intellectual property, investigations and property, each with a fixed fee plus VAT",
      },
    ],
    metrics: [
      { value: "95%", caption: "Extraction accuracy", note: "* on the evaluated set, Jan 2026" },
      { value: "100+", caption: "Files / month", note: "* in production, at handover" },
      { value: "-30%", caption: "Manual document work", note: "* reported by users, Jan 2026" },
      { value: "50+", caption: "Active users", note: "* legal professionals, Jan 2026" },
    ],
    headlines: {
      constraints: "Why a better prompt was never the answer",
      tradeoffs: "What accuracy cost",
      build: "The five modules",
      result: "What Golegal measured",
    },
    metricsNote:
      "The 95% is exact-match accuracy on the evaluated set, not every accepted document type. The −30% is user-reported rather than instrumented. File and active-user counts are platform records from January 2026.",
    reflection:
      "I’d build the evaluation harness before the pipeline. Tuning by feel delayed clear decisions until a scored regression set existed.",
  },
  {
    slug: "muterpe",
    name: "Muterpe",
    accentWord: "Muterpe",
    tagline: "AI Image Generation SaaS",
    summary:
      "An AI model-training and image-generation SaaS built from the ground up, with per-user training, streamed generation and usage-based billing.",
    role: "Founding Engineer",
    timeline: "2023 – Present",
    status: "Live, monetized",
    stack: ["Next.js", "React", "PostgreSQL", "OpenAI", "Fal.ai", "AWS S3"],
    indexMetrics: ["200+ users", "$5K+ revenue", "99% uptime"],
    image: img.muterpe,
    alt: "Muterpe AI image generation interface with result grid",
    problemHeadline: "Generic models don’t hold a likeness",
    problem:
      "Generic image generators don’t hold a brand or a person’s likeness. Muterpe needed per-user model training, plus a generation pipeline fast enough that users wouldn’t abandon mid-flow.",
    context: [
      { k: "ROLE", v: "Founding engineer — pipeline, prompt shaping, storage, metering and billing, end to end" },
      { k: "USERS", v: "200+ on self-serve signup, paying for what they generate rather than for a seat" },
      {
        k: "OWNED",
        v: "Training and generation pipeline · async job queue · asset storage and delivery · usage metering and billing",
      },
      {
        k: "NOT MINE",
        v: "The models themselves — training and inference run on Fal.ai, prompt shaping goes through OpenAI",
      },
      { k: "PRODUCT", v: "Train a model on your own images once, then generate against it, billed per generation" },
    ],
    constraints: [
      {
        title: "Every signup costs money before it earns any",
        body: "Per-user training consumes GPU time before a customer generates anything, setting a real floor under pricing and free access.",
      },
      {
        title: "The wait is at the front, where people leave",
        body: "Training takes minutes before the first result, so progress and responsive background work are essential to first-run retention.",
      },
      {
        title: "The training set is photographs of the user",
        body: "Training images contain personal data, so storage and delivery were designed around access control rather than convenience.",
      },
    ],
    approach:
      "Training and generation run as queued jobs, while progress and partial results stream to the interface. Slow model work never blocks the application.",
    tradeoffs: [
      {
        decision: "Rent the model runtime rather than run GPUs",
        instead: "Self-host training and inference, which is cheaper per run at volume and gives you the whole stack",
        cost: "Fal.ai sets the price floor and controls cold starts and queue depth.",
        bought: "The product shipped without GPU capacity planning, driver maintenance or idle infrastructure cost.",
      },
      {
        decision: "Train a model per user",
        instead: "Prompt one shared model with the user's photos as reference images, which needs no training step at all",
        cost: "Each account incurs training time, GPU cost, storage and a slower first run.",
        bought: "Likeness remains more consistent than reference-image prompting, the product’s core value.",
      },
      {
        decision: "Stream partial results instead of returning a finished batch",
        instead: "Wait for the set to complete and render it at once, which is far simpler to reason about",
        cost: "The interface must handle partial state, cancellation and mid-stream failures.",
        bought: "Time to first visible result improved by about 40% without changing the model.",
      },
      {
        decision: "Charge per generation, not per month",
        instead: "A flat subscription, which is easier to sell and far easier to build",
        cost: "Metering must handle partial failures, retries and cancellations in the request path.",
        bought: "Revenue follows the GPU-backed operation instead of relying on average usage assumptions.",
      },
    ],
    decisions: [
      "Trained one model per user on Fal.ai behind an asynchronous job queue.",
      "Shaped prompts server-side and streamed generated images as they arrived.",
      "Metered generation in the workflow so billing tracks the operation with real unit cost.",
    ],
    diagram: {
      src: "/projects/muterpe-pipeline.svg",
      alt: "Muterpe train and generate pipeline: an upload enqueues a per-user training job on Fal.ai while the interface stays responsive, and generation shapes the prompt through OpenAI, streams results as they land, meters usage for billing and serves every asset from S3",
      caption: "* TRAIN / GENERATE PIPELINE",
    },
    build: [
      {
        title: "Per-user model training",
        body: "Users upload a set, the job queue picks it up, and training progress streams back to the UI. Nothing about the app is blocked while a model bakes.",
      },
      {
        title: "Generation that feels immediate",
        body: "Prompts are shaped server-side before they hit the generation provider, and results stream in as they land. Perceived speed improved ~40% without changing the underlying model.",
      },
      {
        title: "Metering, added later than it should have been",
        body: "Billing arrived after the pipeline, so partial failures, retries and cancellations needed rules after the fact. Metering now works, but should have shaped the workflow from the start.",
      },
    ],
    headlines: {
      constraints: "What a per-user model costs before it earns",
      tradeoffs: "Where quality beat instant",
      build: "Train, then generate",
      result: "What Muterpe measured",
    },
    metricsNote:
      "Users and revenue come from platform and billing records. The ~40% measures time to first visible result against the first release, not model throughput. Uptime is the rolling twelve-month monitoring figure.",
    metrics: [
      { value: "200+", caption: "Users", note: "* self-serve signup" },
      { value: "$5K+", caption: "Revenue", note: "* usage-based" },
      { value: "99%", caption: "Uptime", note: "* rolling 12 months" },
      // Keeps the two qualifiers the write-up above states: it is perceived
      // speed, from streaming, and it is approximate. "Faster generation" flat
      // was a different and larger claim than the one that was measured.
      { value: "~40%", caption: "Faster, perceived", note: "* streaming, vs. first release" },
    ],
    reflection:
      "Usage metering arrived too late and cost more to retrofit than to design upfront. Next time I would meter first and price second.",
  },
  {
    slug: "volumize",
    name: "Volumize",
    accentWord: "Volumize",
    tagline: "Telehealth E-Commerce Platform",
    summary:
      "A telehealth commerce platform connecting medical intake, clinician approval, prescriptions, payments, despatch and subscriptions across customer and operations apps.",
    role: "Full-Stack Engineer",
    timeline: "Feb 2026 – Present",
    status: "Live",
    liveUrl: "https://volumize.co.uk",
    liveLabel: "volumize.co.uk",
    stack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "MongoDB",
      "Mongoose",
      "Socket.IO",
      "Stripe",
      "Royal Mail API",
      "AWS S3",
      "Turborepo",
      "RAG",
      "LLM",
      "Sentry",
    ],
    /*
     * Outcomes, not repository statistics. This used to lead with route-file
     * counts and a dependency-audit score — true, but they describe the shape
     * of the codebase rather than anything the business got. These are what the
     * platform actually changed once it was running.
     */
    indexMetrics: ["250+ subscriptions", "£31K+ revenue", "4 back-office roles"],
    image: img.volumize,
    alt: "Volumize telehealth commerce dashboard",
    problemHeadline: "Intake and checkout live in different systems",
    problem:
      "Medical intake, checkout, clinical approval and fulfilment often live in separate tools. That fragments the patient journey, slows prescription handoff and makes payments, subscriptions and refunds difficult to reconcile.",
    context: [
      {
        k: "OWNED",
        v: "The lifecycle end to end: intake and the RAG recommendation, checkout and subscriptions, despatch, the role-based back office, monitoring and the content admin",
      },
      { k: "ROLES", v: "Four in one back office — admin · pharmacist · doctor · marketing" },
      {
        k: "NOT MINE",
        v: "The clinical decision and the dispensing — prescribing is done by the clinicians, fulfilment by a GPhC-registered pharmacy",
      },
      { k: "PRODUCT", v: "£19/mo base on 3- and 6-month courses, despatched a cycle ahead" },
      { k: "SURFACES", v: "A customer app and an operational back office over three shared packages" },
    ],
    constraints: [
      {
        title: "A missed dose is the failure that matters",
        body: "Treatment continuity made a late renewal more serious than an ordinary delivery delay. It drove early despatch, idempotent retries and monotonic order states.",
      },
      {
        title: "The AI cannot be the prescriber",
        body: "AI can summarise intake and suggest a plan, but a clinician must make the prescribing decision. The workflow speeds up review without removing that control.",
      },
      {
        title: "Enough users that failures are not theoretical",
        body: "Approvals, despatches and renewals are always in flight. Health checks and error tracking had to surface failures before patients reported them.",
      },
    ],
    approach:
      "I built a customer app and role-based back office over shared auth, data models and UI packages. The subscription lifecycle was designed around treatment continuity rather than billing dates.",
    tradeoffs: [
      {
        decision: "Despatch the next cycle two weeks before the current one runs out",
        instead: "Ship on the renewal date, the way a subscription normally works",
        cost: "More stock stays in transit, and a late cancellation can arrive after despatch.",
        bought: "Subscribers receive the next cycle before the current supply ends, reducing treatment gaps.",
      },
      {
        decision: "Retry despatch repeatedly rather than failing to a human",
        instead: "Fail the job on the first error and raise it for someone to handle",
        cost: "Retries must be idempotent to avoid duplicating physical orders.",
        bought: "Transient carrier or pharmacy failures recover without creating a manual backlog.",
      },
      {
        decision: "The questionnaire recommends, a clinician decides",
        instead: "Let the pipeline issue the plan directly for a doctor to rubber-stamp",
        cost: "Throughput remains bounded by clinician review.",
        bought: "Prescribers receive a reasoned recommendation without surrendering the regulated decision.",
      },
      {
        decision: "Health-check services and error tracking from the start",
        instead: "Rely on customer reports and server logs, which is free",
        cost: "Monitoring adds services and alert thresholds that require maintenance.",
        bought: "Operational failures surface before they become missed deliveries.",
      },
    ],
    decisions: [
      "Modelled intake, review, prescription and fulfilment as one explicit order state machine.",
      "Shared auth, data and UI packages across the customer app and back office.",
      "Separated customer and staff sessions into distinct trust boundaries.",
      "Executed refunds against the same Stripe environment as the original charge.",
      "Integrated Royal Mail label generation and tracking with the order lifecycle.",
    ],
    diagram: {
      src: "/projects/volumize-lifecycle.svg",
      alt: "Volumize order lifecycle: signup, medical questionnaire and checkout, then doctor review branching to either prescription, pharmacy handoff and Royal Mail despatch feeding subscription renewal, or rejection and refund",
      caption: "* ONE ORDER, END TO END",
    },
    build: [
      {
        title: "Two apps, one domain layer",
        body: "Separate customer and operations deployments share auth, database and UI packages. Fifteen Mongoose models define the domain once.",
      },
      {
        title: "Intake to delivery, as one pipeline",
        body: "Signup, medical intake, checkout, review, prescription and pharmacy handoff form one stateful pipeline. Royal Mail labels and tracking update the order directly; renewals and refunds are explicit branches.",
      },
      {
        title: "A questionnaire that recommends, not just records",
        body: "A retrieval-augmented pipeline compares intake answers with treatment indications and contraindications, then gives the clinician a suggested plan and reasoning. The prescriber still reviews and decides.",
      },
      {
        title: "Four roles, one back office",
        body: "Admin, pharmacist, doctor and marketing roles share one back office with server-enforced route permissions. Clinical data never depends on hidden interface controls for protection.",
      },
      {
        title: "Content the marketing team owns",
        body: "The marketing team manages blog and campaign content from the same admin without requiring an engineering release.",
      },
      {
        title: "Security hardening pass",
        body: "A phased dependency upgrade cleared every high and moderate finding across 1,127 packages. Query optimisation and edge caching also took 1.8 seconds off page load and 35% off API response time.",
      },
    ],
    metrics: [
      /*
       * Revenue first, then the two operational numbers that produced it. The
       * build statistics that used to sit here — 94 route files, a 97% cut in
       * vulnerabilities, an audit score of 99 — are still true and still
       * described in the build blocks above; they are just not what a clinic
       * or a client is asking about. The saved admin hours and the page-load
       * improvement moved into those blocks for the same reason.
       */
      {
        value: "250+",
        caption: "Live subscriptions",
        note: "* £19/mo base, 3- and 6-month plans",
      },
      { value: "£31K+", caption: "Subscription revenue", note: "* booked across those plans" },
      {
        value: "-45%",
        caption: "Approval turnaround",
        note: "* review to prescription, vs. manual handoff",
      },
      {
        value: "-85%",
        caption: "Order despatch time",
        note: "* after Royal Mail label + tracking sync",
      },
      { value: "4", caption: "Back-office roles", note: "* admin · pharmacist · doctor · marketing" },
    ],
    headlines: {
      constraints: "What medicine on a schedule rules out",
      tradeoffs: "Where continuity beat convention",
      build: "The lifecycle, part by part",
      result: "What Volumize measured",
    },
    metricsNote:
      "Subscriptions and revenue are booked platform figures. The −45% compares clinician review with reasoned recommendations against raw intake; the −85% compares integrated Royal Mail despatch with manual labels and tracking. Both are before-and-after averages, not guarantees.",
    reflection:
      "The dependency cleanup was reactive after 34 findings accumulated. I would enforce audit thresholds in CI so the graph cannot drift that far again.",
  },
  {
    slug: "wisdomup",
    name: "WisdomUp",
    accentWord: "WisdomUp",
    tagline: "Multi-Service E-Commerce Platform",
    summary:
      "A three-service commerce platform — storefront, transactional API and CMS admin — built around a checkout designed for its edge cases, not just its happy path.",
    role: "Full-Stack Product Engineer",
    timeline: "2026 – Present",
    status: "In development",
    inDevelopment: true,
    stack: [
      "Next.js",
      "TypeScript",
      "Express 5",
      "MongoDB",
      "Payload CMS",
      "Stripe",
      "Redux Toolkit",
      "RTK Query",
      "Zod",
    ],
    indexMetrics: ["3 services", "8-layer payment guard", "14 settlement tests"],
    image: img.wisdomup,
    alt: "WisdomUp storefront and admin dashboard",
    problemHeadline: "Checkout breaks in the edge cases",
    problem:
      "Commerce systems often couple content changes to releases and treat payment callbacks as orderly. Duplicate, delayed or mismatched events then become financial risk, while a monolith makes either concern harder to change safely.",
    context: [
      { k: "ROLE", v: "Full-stack product engineer across all three services" },
      {
        k: "OWNED",
        v: "Storefront · Express transactional API · Payload CMS admin · the settlement path that runs between them",
      },
      { k: "SURFACES", v: "Three independently deployable services over one shared MongoDB" },
      {
        k: "SCOPE",
        v: "Catalogue derived from host and market, so one codebase serves a local and a global storefront",
      },
      {
        k: "STATUS",
        v: "In development — the payment path is hardened and tested, and has not yet carried production traffic",
      },
    ],
    constraints: [
      {
        title: "The money settles once; the events describing it do not",
        body: "Stripe events can be duplicated, delayed or reordered. Every settlement write therefore had to be safe to replay without charging twice or advancing an unpaid order.",
      },
      {
        title: "A campaign cannot wait for a release",
        body: "Marketing needed to change banners, FAQs and promotions without engineering releases, while the storefront had to tolerate incomplete CMS data.",
      },
      {
        title: "Nothing here has production traffic to check it against",
        body: "The payment controls are tested but not yet proven by production traffic. The case study reports implementation counts, not business outcomes.",
      },
    ],
    approach:
      "I separated storefront, transactional API and CMS, then designed settlement for duplicate and out-of-order events. Money writes are idempotent and the order state machine only advances through explicit transitions.",
    tradeoffs: [
      {
        decision: "Settle down two independent paths",
        instead: "Trust the webhook alone, which is what Stripe's own documentation recommends and is one code path instead of two",
        cost: "Two writers must be idempotent and agree on what has already happened.",
        bought: "A closed browser or delayed webhook cannot lose a paid order.",
      },
      {
        decision: "Order status only moves forward",
        instead: "Apply whatever the latest event says, which is the obvious reading of an event stream",
        cost: "Refunds and cancellations need explicit transitions instead of direct status assignment.",
        bought: "Stale events become no-ops and cannot regress an order that has already advanced.",
      },
      {
        decision: "Three services over one shared database",
        instead: "A database per service, which is what service separation is normally taken to mean",
        cost: "Schema changes require coordination and service isolation is incomplete.",
        bought: "Checkout avoids distributed transactions while services retain separate deployment and bounded ownership.",
      },
      {
        decision: "Content is data the CMS owns, not components the repository owns",
        instead: "Hard-code the sections and ship a release when marketing wants a change",
        cost: "The storefront needs typed contracts, validation and defensive rendering for optional content.",
        bought: "Eleven collections plus site settings let marketing publish without an engineering release.",
      },
    ],
    decisions: [
      "Separated the storefront, Express API and Payload CMS into independent deployables over one database.",
      "Settled payments through immediate confirmation and webhook reconciliation.",
      "Guarded settlement with verification, idempotency, replay protection and monotonic order state.",
      "Derived catalogue scope from host and market and enforced it again at checkout.",
    ],
    diagram: {
      src: "/projects/wisdomup-settlement.svg",
      alt: "WisdomUp architecture: a storefront, an Express transactional API and a Payload CMS admin over one shared database, with payment settled down two independent paths behind eight guard layers and an order status that only moves forward",
      caption: "* THREE SERVICES + DUAL SETTLEMENT",
    },
    build: [
      {
        title: "Two paths to settled",
        body: "Client confirmation records payment immediately; the webhook reconciles signature, amount, ownership and transaction identity. Fourteen tests cover this settlement logic.",
      },
      {
        title: "Merchandising without a deploy",
        body: "Eleven CMS collections plus editable navigation and site settings cover merchandising, with CSV import for bulk catalogue work.",
      },
      {
        title: "Storefront surface",
        body: "The storefront includes search, filtering, cart, wishlist, moderated reviews and resumable guest checkout. Promotions are validated server-side for eligibility and value.",
      },
    ],
    metrics: [
      { value: "3", caption: "Deployable services", note: "* storefront · API · CMS" },
      { value: "8", caption: "Payment guard layers", note: "* signature to state machine" },
      { value: "14", caption: "Settlement tests passing", note: "* confirmation logic" },
      {
        value: "2",
        caption: "Independent paths to settled",
        note: "* client confirmation · webhook fallback",
      },
    ],
    headlines: {
      constraints: "What a payment system has to assume",
      tradeoffs: "Where correctness beat the simpler path",
      build: "The three services",
      result: "What is built — and what is not yet observed",
    },
    metricsNote:
      "These are implementation counts, not production outcomes: three deployables, eight settlement guards, fourteen passing tests and two paths to a settled order. Tests verify the written logic, not its assumptions under live traffic.",
    reflection:
      "The payment layer is hardened but not yet observed in production. I would instrument checkout success, reconciliation accuracy and promotion conversion before adding more features.",
  },
  {
    slug: "alfa",
    name: "Alfa",
    accentWord: "Alfa",
    tagline: "Multi-Role Fintech Platform",
    summary:
      "A role-aware fintech platform for personal, business and admin journeys over Python microservices. I own sessions, authorisation, onboarding, verification, document handling and the client data layer.",
    role: "Full-Stack Engineer — Python microservices & Next.js client",
    timeline: "Feb 2026 – Present",
    status: "In development",
    inDevelopment: true,
    stack: [
      "Python",
      "FastAPI",
      "Supabase",
      "GraphQL",
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Redux Toolkit",
      "RTK Query",
      "Zod",
      "Tailwind v4",
      "AWS S3",
    ],
    /*
     * Services delivered and interfaces designed, rather than the shape of the
     * repository. "4 route groups" described a directory layout; these describe
     * what the platform does and what was built to make it do it.
     */
    indexMetrics: ["6 isolated capabilities", "2 authorisation layers", "4 measures instrumented"],
    image: img.alfa,
    alt: "Alfa fintech dashboard",
    problemHeadline: "Acting as the wrong account is not a UI bug",
    problem:
      "A user can hold personal and business accounts, have neither selected and be verified on only one. In a money product, unresolved identity can expose the wrong balance or payment surface. Account, role and verification state must settle before any transaction can begin.",
    context: [
      { k: "ROLE", v: "Full-stack engineer — the FastAPI services and the Next.js client on top of them" },
      {
        k: "OWNED",
        v: "Session and authorisation model · onboarding and verification · document handling · the client data layer",
      },
      {
        k: "NOT MINE",
        v: "The banking rails — issuing, funding and exchange rates sit behind providers, and the regulated permissions are the operator's",
      },
      { k: "SURFACES", v: "Three journeys out of one architecture — personal, business and admin" },
      {
        k: "STATUS",
        v: "In development and pre-traffic, which is why the measures below are instrumented rather than reported",
      },
    ],
    constraints: [
      {
        title: "Verification gates money, not features",
        body: "Payment surfaces do not render until verification passes for the selected account. Personal and business verification states remain independent.",
      },
      {
        title: "Identity documents are the most sensitive thing here",
        body: "Passports, incorporation papers and address evidence pass through server-controlled handlers so storage credentials never reach the browser.",
      },
      {
        title: "A capability failing must not look like the bank being down",
        body: "FX, cards and top-ups depend on different providers. Each capability must degrade independently so one outage does not take down the platform.",
      },
    ],
    tradeoffs: [
      {
        decision: "Resolve identity before a money surface exists",
        instead: "Render the dashboard and let each page check what it is allowed to show",
        cost: "Identity resolution adds a step before the first meaningful application screen.",
        bought: "Transaction controls never render for an unselected or uncleared account.",
      },
      {
        decision: "Authorise twice — at the route, and at the row",
        instead: "Trust the route guard, since the client cannot reach the data without passing it",
        cost: "Route and row-level policies both require maintenance.",
        bought: "An application bug cannot expose another account’s financial records.",
      },
      {
        decision: "One service per financial capability",
        instead: "One payments service, which is far less to run for a team this size",
        cost: "Six deployables add operational overhead and coordinate some releases.",
        bought: "Provider failures remain inside one capability instead of taking down balances, transfers and cards together.",
      },
      {
        decision: "Identity documents move through the server",
        instead: "Upload straight from the browser to object storage with a client-held credential",
        cost: "Route handlers must manage file size and streaming.",
        bought: "No browser-held credential can reach the identity-document bucket.",
      },
    ],
    approach:
      "Identity resolves once before any money-moving interface renders. Edge middleware checks token presence; a central guard resolves account, role and verification. Six FastAPI capabilities sit behind GraphQL, with authorisation enforced at both route and row level.",
    decisions: [
      "Resolved role, account and verification once, before any money-moving screen renders.",
      "Limited edge middleware to checking whether a token exists.",
      "Placed 10+ GraphQL APIs in front of six FastAPI capabilities.",
      "Used one RTK Query base API across seven client domains.",
      "Instrumented authorisation rate, transfer p95, reconciliation breaks and KYC completion before launch.",
    ],
    diagram: {
      src: "/projects/alfa-services.svg",
      alt: "Alfa architecture: an edge token gate and a single client-side guard resolve role and session once per visit, one RTK Query base API serves seven domains, and 10+ GraphQL APIs sit in front of six independently deployable FastAPI services over Supabase",
      caption: "* AUTH + SERVICE TOPOLOGY",
    },
    build: [
      {
        title: "Hybrid auth model",
        body: "After optional 2FA, a bootstrap provider fetches the user once. A central guard then resolves admin, dashboard, onboarding or account selection.",
      },
      {
        title: "One API, seven domains",
        body: "Auth, business, cards, transactions, schedules, wallet and admin inject endpoints into one RTK Query base API with shared caching and invalidation.",
      },
      {
        title: "Verification, and the documents it runs on",
        body: "Personal and business onboarding use separate paths and independently gate payment access. Identity documents move through Next.js route handlers with the AWS SDK, keeping bucket credentials off the client.",
      },
      {
        title: "Four route groups, one set of rules",
        body: "Auth, onboarding, dashboard and admin route groups share Zod schemas, keeping validation consistent from signup through later edits.",
      },
      {
        title: "Money movement surfaces",
        body: "Shared shells and form primitives support transfers, payment requests, scheduled payments, transaction history and card management across account types.",
      },
      {
        title: "The four numbers this gets judged on",
        body: "The platform emits authorisation rate, transfer p95, reconciliation break rate and KYC completion. These measures exist before traffic, but do not yet have reportable values.",
      },
      {
        title: "p95, not the average",
        body: "Transfer latency uses p95 from service entry to ledger write. Reconciliation break rate tracks movements where provider and platform records disagree at day end.",
      },
      {
        title: "Verification, measured per step",
        body: "KYC completion is measured per onboarding step because verification gates funding. Alfa is pre-traffic, so only events and thresholds exist; no outcome is claimed yet.",
      },
    ],
    metrics: [
      /*
       * Controls, which is what this domain measures. A payments platform is
       * judged on what it makes impossible — funds moving from an account the
       * user did not select, one account reading another's rows, a rate
       * provider taking the whole product down — not on how much was built.
       * The four figures a fintech publishes alongside these — authorisation
       * rate, p95 on the transfer path, reconciliation break rate and KYC
       * completion — need production traffic to mean anything. The last tile
       * therefore counts the instrumentation, and the build block above defines
       * each measure and its threshold. Printing a value would be inventing one.
       */
      {
        value: "0",
        caption: "Money surfaces before identity resolves",
        note: "* the guard settles the account, then the screen exists",
      },
      {
        value: "2",
        caption: "Layers authorising a read",
        note: "* route guard, and row-level rules at the data",
      },
      {
        value: "6",
        caption: "Capabilities that fail alone",
        note: "* an FX outage is not a transfers outage",
      },
      {
        value: "4",
        caption: "Service levels instrumented",
        note: "* auth rate · transfer p95 · recon breaks · KYC completion",
      },
    ],
    headlines: {
      constraints: "What moving money rules out",
      tradeoffs: "Where safety beat simplicity",
      build: "What Alfa is made of",
      result: "What Alfa guarantees — and what it will measure",
    },
    metricsNote:
      "Alfa has no live traffic. The first three values are verifiable architecture properties; the fourth counts instrumentation, not output. Authorisation, latency, reconciliation and KYC will carry values only after production traffic exists.",
    reflection:
      "Money movement and authentication need broader integration and end-to-end coverage. That is the next priority before onboarding analytics or staged rollout controls.",
  }
];

/**
 * Reading order, and the numbering that comes with it.
 *
 * The case-study page shows two numerals for the same project: a position
 * counter in the sticky bar ([02 / 06]) and the authored [CASE STUDY nn] tag.
 * Those were separate values — declaration order for one, a hand-written
 * `index` field for the other — and four of the six disagreed. Deriving the
 * index from this list makes them the same number by construction, and makes
 * prev/next walk the projects in the order the site actually presents them.
 */
const ORDER = ["carder", "volumize", "golegal", "alfa", "wisdomup", "muterpe"] as const;

export const projects: Project[] = ORDER.map((slug, i) => {
  const project = authored.find((p) => p.slug === slug);
  if (!project) throw new Error(`ORDER lists a slug with no project: ${slug}`);
  return { ...project, index: String(i + 1).padStart(2, "0") };
});

/*
 * The guard above catches a slug with no project. This catches the direction
 * that fails quietly: a project added to `authored` and forgotten here would
 * simply vanish — no route from generateStaticParams, no card on the index, no
 * entry in the sitemap, and nothing anywhere to say so.
 */
if (projects.length !== authored.length) {
  const missing = authored.map((p) => p.slug).filter((slug) => !ORDER.includes(slug as never));
  throw new Error(`Projects missing from ORDER: ${missing.join(", ")}`);
}

const bySlug = Object.fromEntries(projects.map((p) => [p.slug, p])) as Record<string, Project>;

/**
 * The four the index leads with, in the order it leads with them.
 *
 * `ORDER` above is *routing* order — it feeds `generateStaticParams`, the
 * case-study numbering and prev/next, so it stays put. This is
 * presentation order, and the two are allowed to differ: WisdomUp and Muterpe
 * still have full case studies, they just no longer earn a pinned card on the
 * index. They surface through `otherWork` instead, which links straight at
 * those same pages.
 */
export const featuredProjects: Project[] = ["carder", "volumize", "golegal", "alfa"].map(
  (slug) => bySlug[slug],
);

export type OtherWork = {
  name: string;
  tagline: string;
  /** One line. This list is an index, not a second case-study section. */
  note: string;
  stack: string[];
  status: string;
  href: string;
  /** Case studies link inward; everything else opens in a new tab. */
  external?: boolean;
  hrefLabel: string;
};

/**
 * Shipped work that isn't the argument the index is making. Two of these have
 * full case studies and point at them; the third is a live site and points at
 * itself.
 */
export const otherWork: OtherWork[] = [
  {
    name: "WisdomUp",
    tagline: "Multi-Service E-Commerce Platform",
    note: "Storefront, transactional API, and CMS admin as three deployable services, with settlement guarded down two paths so a dropped browser never loses an order.",
    stack: ["Next.js", "Express 5", "MongoDB", "Payload CMS", "Stripe"],
    status: "In development",
    href: "/work/wisdomup",
    hrefLabel: "Read the case study",
  },
  {
    name: "LightspeedGo",
    tagline: "Logistics & Delivery Platform",
    note: "Marketing and booking surface for a courier operation — live, and the front door for the dispatch flow behind it.",
    stack: ["Next.js", "TypeScript", "Tailwind"],
    status: "Live",
    href: "https://lightspeedgo.com",
    external: true,
    hrefLabel: "lightspeedgo.com",
  },
  {
    name: "Muterpe",
    tagline: "AI Image Generation SaaS",
    note: "Per-user model training and generation on Fal.ai, monetized usage-based, with an async queue so a baking model never blocks the UI.",
    stack: ["Next.js", "PostgreSQL", "Fal.ai", "OpenAI", "AWS S3"],
    status: "Live, monetized",
    href: "/work/muterpe",
    hrefLabel: "Read the case study",
  },
];

/** One node of the agent's state machine, as the index replays it. */
export type TraceStep = {
  id: string;
  label: string;
  /** What the node actually emitted — shown as the span's result line. */
  detail: string;
  ms: number;
  tokens?: number;
  /** The human-approval interrupt. The replay stops here until someone taps. */
  gate?: boolean;
};

/**
 * mailagent — in build, not shipped, and listed that way on purpose.
 *
 * The interesting claim here isn't "an LLM reads your email", it's the
 * engineering around it: a scoring harness that existed before the extractor,
 * a retrieval comparison whose losing arm shipped disabled, and cost accounting
 * that records an unpriced call as NULL rather than lying with a zero. The
 * index replays the graph instead of describing it.
 */
export const comingSoon = {
  name: "mailagent",
  tagline: "Human-in-the-Loop Scheduling Agent",
  status: "In build",
  summary:
    "Reads Gmail, spots meeting requests, extracts the details, checks the calendar for conflicts, and sends a Telegram card with Confirm / Edit / Cancel. Nothing touches the calendar without a human tap.",
  stack: [
    "Python 3.12",
    "FastAPI",
    "LangGraph",
    "Gemini",
    "Postgres + pgvector",
    "Gmail & Calendar APIs",
    "Telegram Bot API",
    "Next.js",
  ],
  trace: [
    {
      id: "classify",
      label: "classify",
      detail: 'intent="schedule_meeting" · confidence 0.94',
      ms: 412,
      tokens: 318,
    },
    {
      id: "extract",
      label: "extract",
      detail: 'title="Design sync" · Thu 14:00–14:45 GMT · 3 attendees',
      ms: 1180,
      tokens: 902,
    },
    {
      id: "retrieve",
      label: "retrieve",
      detail: "pgvector · 5 prior threads · hit@5 1.00 (fusion off)",
      ms: 96,
    },
    {
      id: "conflict_check",
      label: "conflict_check",
      detail: "1 overlap — “1:1 · Ali” Thu 14:30. Proposing 15:00.",
      ms: 240,
    },
    {
      id: "human_approval",
      label: "human_approval",
      detail: "interrupt — awaiting Telegram callback",
      ms: 0,
      gate: true,
    },
    {
      id: "act",
      label: "act",
      detail: "calendar.events.insert · 200 · reply drafted",
      ms: 588,
    },
  ] satisfies TraceStep[],
  /** Numbers that came out of the harness, not out of a pitch. */
  evidence: [
    { value: "92.9%", caption: "Exact-match extraction", note: "* 14 hand-labelled fixtures" },
    { value: "100%", caption: "Retrieval hit@5", note: "* vector-only, 29 queries" },
    { value: "NULL", caption: "Unpriced call cost", note: "* never recorded as 0" },
    { value: "OFF", caption: "RRF fusion, shipped", note: "* built, measured, lost" },
  ],
  /**
   * The most distinctive part of the write-up. Four real production bugs, kept
   * in the reader's view rather than buried in a repo — a portfolio that only
   * lists wins is a portfolio nobody believes.
   */
  broke: [
    {
      title: "Auth bypass",
      body: "An empty Telegram secret matched an empty header, so an unsigned request authenticated cleanly. Fixed by refusing to start when the secret is unset.",
    },
    {
      title: "Silent batch collapse",
      body: "The Gemini SDK quietly folded an embedding batch, returning fewer vectors than inputs with no error. Caught by a length assertion that should have been there first.",
    },
    {
      title: "tsquery AND vs OR",
      body: "A Postgres full-text query built with the wrong operator flipped a benchmark result. The BM25 arm looked worse than it was for two days.",
    },
    {
      title: "A confident wrong answer",
      body: "An A/B run picked a winner on one pass. Repeating it exposed fixture-level variance wide enough to swallow the difference — the result was noise wearing a decision.",
    },
  ],
} as const;

export const getProject = (slug?: string) => projects.find((p) => p.slug === slug);

export const projectNeighbours = (slug: string) => {
  const i = projects.findIndex((p) => p.slug === slug);
  if (i < 0) return { prev: undefined, next: undefined, position: 0 };
  return {
    prev: projects[(i - 1 + projects.length) % projects.length],
    next: projects[(i + 1) % projects.length],
    position: i + 1,
  };
};
