/**
 * Project content.
 *
 * IMAGES: the six screenshots below are placeholders generated into
 * `public/projects/`. Drop your real files into that folder and change the
 * paths here — that is the only edit needed (e.g. "/projects/carder.jpg").
 */
const img = {
  carder: "/projects/carder-hero.png",
  carderMedia: "/projects/carder-media.png",
  carderTiers: "/projects/carder-tiers.png",
  golegal: "/projects/golegal-editor.webp",
  muterpe: "/projects/muterpe.svg",
  alfa: "/projects/alfa.svg",
  volumize: "/projects/volumize.svg",
  wisdomup: "/projects/wisdomup.svg",
} as const;

export const projectImages = img;

export type Metric = { value: string; caption: string; note?: string };

/*
 * `image` is optional. Some of what a build is made of has no public screen to
 * show — an internal back office, a billing path — and captioning an unrelated
 * picture as that thing is worse than showing nothing. A block without an image
 * renders full width instead.
 */
export type BuildBlock = { title: string; body: string; image?: string; alt?: string };

export type Project = {
  slug: string;
  index: string;
  name: string;
  accentWord: string;
  tagline: string;
  summary: string;
  role: string;
  timeline: string;
  status: string;
  inDevelopment?: boolean;
  liveUrl?: string;
  liveLabel?: string;
  /** The URL is a login wall, not a public page. Say so before it is clicked. */
  liveGated?: boolean;
  stack: string[];
  indexMetrics: string[];
  image: string;
  alt: string;
  problem: string;
  problemHeadline: string;
  approach: string;
  decisions: string[];
  diagram?: { src: string; alt: string; caption: string };
  build: BuildBlock[];
  metrics: Metric[];
  /*
   * Where the numbers above came from, and what they are not.
   *
   * A percentage with no baseline and no method is one a reader discounts, and
   * every case study here carries several. This is the line that says which
   * are platform records, which are self-reported, and which are counts of
   * what exists rather than readings of what happened.
   */
  metricsNote?: string;
  /**
   * Per-project section headings.
   *
   * These default to one phrasing for all six, which was fine when two case
   * studies carried the format and became a template once all six did. A
   * rescue and a greenfield build should not have the same silhouette, so each
   * project can name its own sections.
   */
  headlines?: {
    constraints?: string;
    tradeoffs?: string;
    build?: string;
    result?: string;
  };
  reflection: string;

  /*
   * The three sections below are what separate an account of a job from a list
   * of tasks completed, and all three are optional so a case study can be
   * upgraded one at a time rather than all six at once.
   */

  /** Team, scale and ownership. What a reader needs before the problem means anything. */
  context?: { k: string; v: string }[];
  /**
   * What could not be done. A build with no stated constraints reads as a
   * greenfield exercise; naming them is what shows the work was real.
   */
  constraints?: { title: string; body: string }[];
  /**
   * Decisions written as decisions: what was chosen, what was rejected, what it
   * cost and what it bought. "Integrated Stripe" is a task. "Chose Stripe as
   * the source of truth over mirroring entitlements locally, and paid for it in
   * network calls" is a decision.
   */
  tradeoffs?: { decision: string; instead: string; cost: string; bought: string }[];
  /** Production failures, kept in the reader's view — the device mailagent already uses. */
  broke?: { title: string; body: string }[];
};

/*
 * The projects as written. The catalogue index is deliberately absent: it is
 * derived from ORDER below, so the number on the page and the number in the
 * counter cannot drift apart again.
 */
const authored: Omit<Project, "index">[] = [
  {
    slug: "carder",
    name: "Carder",
    accentWord: "Carder",
    tagline: "AI Mini-Site Builder",
    summary:
      "An AI site builder for small local businesses: one sentence in, a complete mini-site out in about thirty seconds, on a free tier and two paid ones. I led the backend, the data layer and the billing and media infrastructure it runs on.",
    role: "Backend & Infrastructure Lead",
    timeline: "Nov 2022 – Feb 2026",
    status: "Live",
    liveUrl: "https://carder.app",
    liveLabel: "carder.app",
    stack: ["Laravel", "Next.js", "TypeScript", "Node.js", "Express", "SQL", "Stripe", "AWS S3"],
    /*
     * No revenue figure. The public pricing is $0 / $12 / $29 with a free tier
     * most sites sit on, so any MRR number stated here would be contradicted by
     * the pricing page one click away. Users and adoption are the two claims
     * that survive being checked.
     */
    indexMetrics: ["150+ users", "+40% adoption", "3 metered tiers"],
    image: img.carder,
    alt: "Three sites generated by Carder: a bakery menu, a salon services page, and an Arabic restaurant menu in right-to-left layout",
    problemHeadline: "A list of links is not a business",
    problem:
      "A bakery in Haifa, a salon that books over WhatsApp, a clinic answering the same three questions all day. None of them are offline because they do not care; they are offline because every option asked too much — a designer, a week, a bill, or a page builder they would have to learn. The link-in-bio tools they end up with only point elsewhere: a menu PDF here, a phone number there, every button sending the visitor away from the one place they arrived. Carder's answer is to put the whole business on that link and generate it from a sentence. The engineering problem underneath is less glamorous: the thing had to bill, meter and serve those sites reliably, on a Laravel app that was already carrying paying customers.",
    context: [
      { k: "TEAM", v: "Two engineers on backend, data and infrastructure, alongside product and frontend" },
      { k: "USERS", v: "150+ subscribers across the Middle East and Europe, live throughout" },
      { k: "OWNED", v: "Schema and migrations · billing and quotas · media pipeline · admin back office · CI/CD" },
      { k: "NOT MINE", v: "The generation models and the marketing site — our work was the platform underneath" },
      { k: "RUNTIMES", v: "Laravel core, Node/Express services for specific workloads" },
      {
        k: "PRODUCT",
        v: "Free · Pro $12/mo · Business $29/mo, metered at 5 / 10 / 30 AI generations a month",
      },
    ],
    constraints: [
      {
        title: "The product was live the whole time",
        body: "There was never a window to take it down. Every schema change had to be safe against a running application, and every deploy had to be reversible without restoring a backup — which rules out the in-place migration most tutorials show you.",
      },
      {
        title: "Laravel was not up for replacement",
        body: "The core app was Laravel, the team knew Laravel, and a rewrite would have spent a year to arrive back where it started. Anything new had to sit beside it and speak to the same database rather than replace it.",
      },
      {
        title: "A two-person backend team",
        body: "Two of us on the backend, with no platform team and no dedicated ops behind us. That put a hard ceiling on how much machinery the answer could involve: anything we built, we also had to deploy, monitor and be woken up by.",
      },
    ],
    approach:
      "I kept Laravel as the core and gave the workloads that were hurting it their own home. Media moved out to object storage so uploads stopped occupying request workers, and billing and quota state stopped being things the application tries to remember. Everything I built here was shaped by one rule: the system has to be changeable while it is running, because it never stops running.",
    decisions: [
      "Kept Laravel as the core and moved the two workloads that were hurting it — media and billing — onto their own paths.",
      "Made entitlement a question answered from Stripe on every publish, page save and domain lookup, rather than a flag stored on an account.",
      "Metered AI generation per plan with a monthly reset, and left every existing site fully editable once the allowance was spent.",
      "Built an admin back office over the whole tenancy — accounts, sites, subscriptions, companies — writing through the same billing paths the product uses.",
    ],
    tradeoffs: [
      {
        decision: "Stripe is the source of truth for entitlement",
        instead: "Mirror subscription state into our own tables and trust the local copy",
        cost: "Every entitlement decision is a network call or a cache read, and the cache is another thing that can be wrong.",
        bought: "Three tiers unlock different things — page limits, how many sites, a custom domain, whether the badge shows — and each one is a question asked on nearly every request. Deriving them from Stripe means a lapsed payment cannot leave someone on Business behaviour, a refund takes effect immediately rather than at the next sync, and reconciliation stops being a nightly job that finds yesterday's problems.",
      },
      {
        decision: "Meter generations, not requests",
        instead: "Cap the expensive thing at the API layer, or trust the client not to ask twice",
        cost: "A counter per account per month, with its own reset, and a decision to make every time a generation fails halfway.",
        bought: "The quota sits on the one operation that actually costs money — an AI generation — rather than on traffic, which costs almost nothing. A free account gets five in its first month and a Business account thirty; nobody is rate-limited for browsing their own site, and a failed generation does not silently bill against the allowance.",
      },
      {
        decision: "A Node service for the media pipeline, Laravel for everything else",
        instead: "Handle uploads in Laravel like the rest of the application",
        cost: "A second runtime to deploy, monitor and keep patched — real overhead for a two-person backend team.",
        bought: "An image-heavy profile save stops occupying a PHP-FPM worker that ordinary page requests need. Upload traffic and page traffic stopped competing for the same pool, which is what made the app feel slow under load.",
      },
      {
        decision: "Expand and contract for every schema change",
        instead: "Alter the column and ship it",
        cost: "Three deploys instead of one, and a period where the old and new shapes both exist and both have to be written.",
        bought: "Zero-downtime migrations against live data, and a rollback that is just the previous deploy rather than a restore from backup — which matters more than the extra deploys when the product is earning.",
      },
      {
        decision: "Signed S3 URLs, delivered from the edge",
        instead: "Proxy the bytes through the application server",
        cost: "Expiring URLs to manage, and a signing endpoint that becomes its own hot path.",
        bought: "The application never touches image bytes at all. Delivery is cached at the edge, storage cost is decoupled from server cost, and a profile with twenty photos costs the API exactly as much as one with none.",
      },
    ],
    broke: [
      {
        title: "Entitlement drifted from billing",
        body: "My first version mirrored subscription state locally and trusted it, which is the obvious design and the one I would have defended in review. Stripe webhooks do not arrive in order, do arrive more than once, and occasionally arrive much later than the event they describe — so the local copy and the billing record disagreed, and the disagreement was invisible until a user complained about access they should or should not have had.",
      },
      {
        title: "The fix was to stop remembering",
        body: "I stopped storing it. Entitlement is now derived from Stripe rather than kept beside it, the webhook handler is idempotent on the event id — it recognises an event it has already applied and does nothing — and an event carrying a state older than the one already recorded is discarded rather than applied. Replaying the same webhook twice is a no-op instead of a bug.",
      },
    ],
    diagram: {
      src: "/projects/carder-architecture.svg",
      alt: "Carder architecture: Laravel core with Node services for media, Stripe as the source of truth for entitlement, signed S3 delivery cached at the edge, and an admin back office writing through the same billing paths",
      caption: "* REQUEST, BILLING AND MEDIA PATHS",
    },
    build: [
      {
        title: "Media that never touches the app",
        body: "Every generated site is photo-heavy by nature — a menu, a gallery, a room, a plate. Uploads go straight to S3 behind signed URLs and delivery is cached at the edge, so the application never handles image bytes at all. A site with twenty photos costs the API exactly what an empty one does, which is what let storage grow without the server bill following it.",
        image: img.carderMedia,
        alt: "Photo-heavy generated sites: a photographer's portfolio, a bakery menu and a yoga studio schedule",
      },
      {
        title: "Three tiers, asked on every request",
        body: "Free allows one site and four pages; Pro raises it to ten pages and a chosen address; Business unlocks unlimited pages, three sites, a custom domain and the menu scanner. That is not a badge on an account — it is a question the application asks constantly, on every page save, every publish and every domain lookup. Entitlement is derived from Stripe and cached briefly rather than mirrored, so the answer is never staler than the cache and never wrong after a refund.",
        image: img.carderTiers,
        alt: "Sites of differing scope generated by Carder: a single-page studio site, a multi-page law firm site and a dental clinic site",
      },
      {
        title: "An admin panel over the whole tenancy",
        body: "Every account, every site under it, every subscription and the companies those roll up to, in one back office. I built it because the alternative was support running SQL against production: a plan that needs correcting, a site that has to be suspended, a customer asking what they were charged for. Reading the tenancy is one problem and writing to it is a different one — a change made here moves real money and real published pages, so I made the panel work through the same billing and entitlement paths the product does rather than writing around them.",
        // No image, deliberately: the admin panel is internal and has no public
        // screen. Drop a redacted screenshot in here if one ever exists.
      },
      {
        title: "Metering the one expensive operation",
        body: "Generation is the only thing in the product that costs real money per use, so the quota lives there and nowhere else: five in a free account's first month, ten a month on Pro, thirty on Business, reset monthly. Sites stay fully editable once the allowance is gone — running out stops you drafting something new, it does not take away what you already made — and a generation that fails partway is not charged against the count.",
        // No image: generation quota is a billing rule, not a screen. The
        // pricing page states the numbers; nothing shows the meter itself.
      },
    ],
    metrics: [
      { value: "150+", caption: "Users, ME & Europe", note: "* two regions, as of Feb 2026" },
      { value: "+40%", caption: "Adoption growth", note: "* after relaunch, to Feb 2026" },
      { value: "3", caption: "Metered tiers", note: "* free · $12 · $29, 5 / 10 / 30 generations" },
      { value: "0", caption: "Downtime migrations", note: "* expand / contract, against live data" },
    ],
    headlines: {
      constraints: "What a live product would not let us do",
      tradeoffs: "What each choice cost",
      build: "What Carder is made of",
      result: "What Carder measured",
    },
    metricsNote:
      "User count and tier structure are platform records and the public pricing page — both checkable. The +40% is the softest number here and worth reading as such: the analytics that produced it only landed part-way through the project, so it measures adoption from the first instrumented month to February 2026 rather than across the whole rebuild. Zero-downtime migrations counts schema changes shipped against live data, not an uptime percentage.",
    reflection:
      "I’d put the analytics layer in from day one. We shipped adoption features on intuition for the first few months, and the +40% only became legible once instrumentation landed — which means we were probably slower than we needed to be to find it.",
  },
  {
    slug: "golegal",
    name: "Golegal",
    accentWord: "Golegal",
    tagline: "AI Legal Workspace",
    summary:
      "A consumer legal platform where a person with a legal problem drafts the document, gets it reviewed, signs it, tracks what it commits them to, and orders a real solicitor when the AI is not enough. I built five of its modules end to end.",
    role: "Full-Stack & AI Engineer — five modules, end to end",
    timeline: "Dec 2024 – Jan 2026",
    status: "Live",
    liveUrl: "https://go-legal.ai",
    liveLabel: "go-legal.ai",
    stack: ["Nest.js", "Next.js", "PostgreSQL", "OpenAI", "Agentic RAG", "React Flow", "Plate.js"],
    indexMetrics: ["95% accuracy", "-30% manual work", "50+ users"],
    image: img.golegal,
    alt: "The Go Legal AI document editor: a confidentiality agreement open with track changes, beside the Copilot review panel showing traffic-light analysis, a document health score and the individual clause findings behind it",
    problemHeadline: "Generic chat can’t be trusted with legal text",
    problem:
      "Legal teams lose hours to reading, extracting, and reformatting the same document types. Generic LLM chat wasn’t accurate enough to trust with legal text — it hallucinated citations and lost document context.",
    context: [
      {
        k: "OWNED",
        v: "Five modules end to end: document creation and RAG · e-signature and obligation extraction · legal pathways · tasks, calendar and notes · the services marketplace",
      },
      { k: "ALSO BUILT", v: "Payments and the token-metered usage module the paid plans run on" },
      {
        k: "NOT MINE",
        v: "The legal content and the regulated advice — Go Legal Ai is not a law firm, and the services are delivered by independent regulated firms",
      },
      { k: "PRODUCT", v: "Free · Power Up £19/mo · Pro £49/mo, metered in AI credits per action" },
      { k: "REACH", v: "England & Wales for instructed services; document generation across 150+ jurisdictions" },
    ],
    constraints: [
      {
        title: "Plausible is not good enough",
        body: "In most products a wrong AI answer is an annoyance the user corrects. Here the output is a clause someone may sign, so the bar is not fluency — it is whether the thing it asserts is actually true of their document and their jurisdiction. That ruled out the usual answer of a bigger prompt and a better model, and made retrieval quality the whole problem.",
      },
      {
        title: "Every AI action costs real money",
        body: "The expensive operations — drafting, reviewing, extracting — cost per call, and the product sells them as credits. So the cost of a pipeline was never just an infrastructure number to optimise later; it set what a plan could contain and what it had to be priced at. A pipeline that was 30% better and 3x the cost was not an improvement.",
      },
      {
        title: "The legal steps cannot be skipped, only made lighter",
        body: "Drafting, reviewing, signing and tracking obligations are a sequence with real dependencies, and none of them can be removed to make the flow shorter. Whatever was done for the experience had to come out of how the steps are presented, not out of the steps themselves.",
      },
    ],
    approach:
      "The fix wasn’t a better prompt, and I spent longer than I should have proving that to myself. What worked was retrieval that preserves legal structure, and agents that know which extraction path a document belongs to. Around that I built the part that makes it a product rather than a demo: metering the expensive operations honestly, and collapsing a multi-step legal flow into something a non-lawyer will actually finish.",
    tradeoffs: [
      {
        decision: "Sell AI work as credits, priced per action",
        instead: "One flat unlimited subscription, the way most SaaS is sold",
        cost: "Credits are a concept the customer has to learn, and every plan page has to explain them. It is a worse pitch than the word unlimited.",
        bought: "The price/token ratio can be tuned until it works at both ends: heavy users cannot make a plan unprofitable, and light users are not quietly subsidising them. It also means an expensive new capability can ship at a fair price instead of being priced for the worst-case user or not shipping at all.",
      },
      {
        decision: "Tune retrieval for precision, not coverage",
        instead: "Retrieve generously and let the model decide what is relevant",
        cost: "More work in chunking and routing, and an occasional relevant passage that does not surface.",
        bought: "Far fewer confident wrong answers. I optimised for the failure the user can catch: on legal text a passage retrieved without its context can be quoted accurately and still be misleading, and a reader has no way to know. A miss they can see costs them a search. A confident wrong answer costs them the clause.",
      },
      {
        decision: "One working surface for drafting, review and signing",
        instead: "A wizard with a page per step, which is easier to build and easier to reason about",
        cost: "A single screen carrying much more state, and a harder component to keep coherent as the feature set grows.",
        bought: "The user stays in their document. Every hop between pages in a legal flow is somewhere to abandon it, and the whole product depends on people finishing.",
      },
    ],
    decisions: [
      "Chunked documents along their own clause hierarchy, so a retrieved passage arrives carrying the ancestry that makes it mean something.",
      "Routed each document type to a dedicated extraction agent with its own tools and validation schema, rather than one prompt covering everything.",
      "Modelled a legal matter as a pathway graph where every node is an action the platform can perform — draft, run an AI step, order a service, produce a court form.",
      "Extracted obligations and their dates out of executed documents and wrote them into the calendar the user already works in.",
    ],
    diagram: {
      src: "/projects/golegal-rag.svg",
      alt: "Golegal agentic RAG pipeline: documents chunked along their own clause hierarchy so each chunk keeps its ancestry, embedded into PostgreSQL, retrieved with that context intact, then routed by a classifier to a per-document-type agent with its own tools and validation schema",
      caption: "* RETRIEVAL THAT KEEPS THE DOCUMENT SHAPE",
    },
    build: [
      {
        title: "Retrieval that keeps the document’s shape",
        body: "I chunk along the document’s own hierarchy — sections, clauses, sub-clauses — and every chunk carries its ancestry. A retrieved clause therefore arrives with the context that makes it mean something, instead of as a paragraph the model has to guess the position of. That single change is what killed the hallucinated citations: the model stopped being asked to infer context it was never handed.",
      },
      {
        title: "One agent per document type",
        body: "A classifier routes each upload to a dedicated extraction agent, and each agent has its own tool set and its own validation schema. Contracts, filings and correspondence fail in different ways, and one prompt covering all three fails at whichever it was tuned for least. Routing first means an extraction can be validated against what that kind of document is actually supposed to contain.",
      },
      {
        title: "Legal pathways, as a graph you can see",
        body: "A legal problem is a sequence, not a document: send the letter, wait the statutory period, file the form, instruct someone if it does not land. Pathways models that as a React Flow canvas where each node is a real thing the platform can do — draft from a smart template, run an AI step, order a service like asset tracing, produce a court form — and the edges are what has to happen first. The user watches their own case advance through it, step three of six, instead of being handed a checklist and left to it.",
        image: "/projects/golegal-pathways.png",
        alt: "The Legal Pathway builder: a React Flow canvas with a Start node branching into an action, a smart template, an asset-tracing service, an AI step and a court form, connected by dependency edges",
      },
      {
        title: "Signature, and what the signature commits you to",
        body: "Multi-party signing with a certificate and an audit trail is the table-stakes half. The half I thought was worth building is what happens after: the platform reads the executed document and extracts its obligations and their dates — notice periods, renewal windows, payment deadlines — then puts them somewhere they will be seen again. A signed contract is a set of future commitments, and the usual failure is not disputing them, it is forgetting one.",
        image: "/projects/golegal-signature.png",
        alt: "A fully signed document in Go Legal AI showing both signers with timestamps, alongside the Extract obligations action and the signing certificate",
      },
      {
        title: "The deadlines the documents created",
        body: "Extracted obligations land in a calendar with tasks, notes and reminders around them, so the date a document created is tracked in the same place as the work it implies. The dashboard leads with what is overdue and what is coming, because for a person handling their own legal matter the expensive mistake is almost never the drafting — it is missing the date.",
        image: "/projects/golegal-tasks.png",
        alt: "The Tasks and Deadlines module: a calendar view with counters for upcoming deadlines, pending and overdue tasks, and reminders, plus notes and integrations tabs",
      },
      {
        title: "When the AI is not enough, order a person",
        body: "Some problems need a regulated solicitor, and pretending otherwise is how legal tech gets people into trouble — so I built the exit rather than papering over it. The services module is a priced catalogue of real work — a lawyer checking your AI draft, a contract review with tracked mark-up, a letter before action, a statutory demand drafted and served — ordered and paid for in the platform, with the fee credited against the first instruction. Every price carries VAT, jurisdiction is stated up front, and the page says plainly that Go Legal AI is not a law firm.",
        image: "/projects/golegal-services.png",
        alt: "The Legal Services catalogue: fifteen priced services across consultation, contracts, disputes, document services, intellectual property, investigations and property, each with a fixed fee plus VAT",
      },
    ],
    metrics: [
      { value: "95%", caption: "Extraction accuracy", note: "* on the evaluated set, Jan 2026" },
      { value: "100+", caption: "Files / month", note: "* in production, at handover" },
      { value: "-30%", caption: "Manual document work", note: "* reported by users, Jan 2026" },
      { value: "50+", caption: "Active users", note: "* legal professionals, Jan 2026" },
    ],
    headlines: {
      constraints: "Why a better prompt was never the answer",
      tradeoffs: "What accuracy cost",
      build: "The five modules",
      result: "What Golegal measured",
    },
    metricsNote:
      "The 95% is exact-match extraction scored against the evaluated set we built, not a claim about every document type the product accepts — a set I would now call too small, which is what the reflection below is about. The −30% is self-reported by users in feedback rather than measured inside the product, and should be read as an impression rather than an instrument reading. Files per month and active users are platform counts taken at handover in January 2026.",
    reflection:
      "I’d build the evaluation harness before the pipeline, not alongside it. We tuned chunking by feel for too long, and every change felt like a coin flip until there was a scored regression set to argue with.",
  },
  {
    slug: "muterpe",
    name: "Muterpe",
    accentWord: "Muterpe",
    tagline: "AI Image Generation SaaS",
    summary:
      "An AI model-training and image-generation platform I built from the ground up as founding engineer and took to paying users — per-user model training, a generation pipeline fast enough to hold attention, and usage-based billing wired into the flow itself.",
    role: "Founding Engineer",
    timeline: "2023 – Present",
    status: "Live, monetized",
    stack: ["Next.js", "React", "PostgreSQL", "OpenAI", "Fal.ai", "AWS S3"],
    indexMetrics: ["200+ users", "$5K+ revenue", "99% uptime"],
    image: img.muterpe,
    alt: "Muterpe AI image generation interface with result grid",
    problemHeadline: "Generic models don’t hold a likeness",
    problem:
      "Generic image generators don’t hold a brand or a person’s likeness. Muterpe needed per-user model training, plus a generation pipeline fast enough that users wouldn’t abandon mid-flow.",
    context: [
      { k: "ROLE", v: "Founding engineer — pipeline, prompt shaping, storage, metering and billing, end to end" },
      { k: "USERS", v: "200+ on self-serve signup, paying for what they generate rather than for a seat" },
      {
        k: "OWNED",
        v: "Training and generation pipeline · async job queue · asset storage and delivery · usage metering and billing",
      },
      {
        k: "NOT MINE",
        v: "The models themselves — training and inference run on Fal.ai, prompt shaping goes through OpenAI",
      },
      { k: "PRODUCT", v: "Train a model on your own images once, then generate against it, billed per generation" },
    ],
    constraints: [
      {
        title: "Every signup costs money before it earns any",
        body: "Training a model per user is GPU time, and it is spent up front — before the user has generated anything, and whether or not they ever come back. That put a floor under what the product could charge and ruled out the usual free tier that lets anyone train a model to see what happens.",
      },
      {
        title: "The wait is at the front, where people leave",
        body: "Training takes minutes and generation takes seconds, but the minutes come first. A new user's first experience of the product is a wait for something they cannot see progress on, which is the single worst place in a funnel to put one.",
      },
      {
        title: "The training set is photographs of the user",
        body: "People upload their own faces to train a likeness. That is personal data with an obvious worst case, so storage and delivery became a question I had to answer about access rather than about cost — which is a different design from the one you reach for when the files are just assets.",
      },
    ],
    approach:
      "Training is slow and generation has to feel instant, so I built the architecture around never letting one block the other. Everything expensive happens on a queue; everything the user is waiting on streams.",
    tradeoffs: [
      {
        decision: "Rent the model runtime rather than run GPUs",
        instead: "Self-host training and inference, which is cheaper per run at volume and gives you the whole stack",
        cost: "A provider dependency on the most important thing in the product, a price floor set by someone else, and no control over cold starts or queue depth when they are busy.",
        bought: "I shipped a product instead of an ML platform. Running our own GPUs would have meant capacity planning, driver management and idle cost from the first user onward — months on infrastructure that Fal.ai already operates better than I could alone, spent before a single person had generated anything.",
      },
      {
        decision: "Train a model per user",
        instead: "Prompt one shared model with the user's photos as reference images, which needs no training step at all",
        cost: "Minutes of GPU time and a stored model per account, spent before the user has produced anything — and a first-run wait where a shared model would have been instant.",
        bought: "The likeness actually holds. Reference-image conditioning gets close and then drifts, which is exactly the failure the product exists to avoid: a generic generator that almost looks like you is not worth paying for. The wait buys the one property the whole thing is sold on.",
      },
      {
        decision: "Stream partial results instead of returning a finished batch",
        instead: "Wait for the set to complete and render it at once, which is far simpler to reason about",
        cost: "Partial state in the interface, and cancellation and error handling that have to work halfway through rather than at a single boundary.",
        bought: "Roughly 40% better perceived speed with no change to the model underneath. The generator did not get faster; the product stopped making people stare at nothing while it worked, which is the half of latency you can fix without a bigger GPU.",
      },
      {
        decision: "Charge per generation, not per month",
        instead: "A flat subscription, which is easier to sell and far easier to build",
        cost: "Metering that has to be correct in the request path, a counter that survives partial failures, and — because it went in late — a retrofit onto a pipeline that was already running.",
        bought: "The one operation with a real unit cost is the one the billing counts, so a heavy user cannot quietly make an account unprofitable and a light user is not subsidising them. On a product where every action spends GPU time, a flat price is a bet on usage rather than a business model.",
      },
    ],
    decisions: [
      "Trained a model per user on Fal.ai behind an async job queue, so a run measured in minutes never occupies the interface.",
      "Shaped prompts server-side through OpenAI before they reach the generation provider, and streamed results back as they land rather than as a finished batch.",
      "Metered generation in the flow itself, so the one operation carrying a real unit cost is the one the billing counts.",
    ],
    diagram: {
      src: "/projects/muterpe-pipeline.svg",
      alt: "Muterpe train and generate pipeline: an upload enqueues a per-user training job on Fal.ai while the interface stays responsive, and generation shapes the prompt through OpenAI, streams results as they land, meters usage for billing and serves every asset from S3",
      caption: "* TRAIN / GENERATE PIPELINE",
    },
    build: [
      {
        title: "Per-user model training",
        body: "Users upload a set, the job queue picks it up, and training progress streams back to the UI. Nothing about the app is blocked while a model bakes.",
      },
      {
        title: "Generation that feels immediate",
        body: "Prompts are shaped server-side before they hit the generation provider, and results stream in as they land. Perceived speed improved ~40% without changing the underlying model.",
      },
      {
        title: "Metering, added later than it should have been",
        body: "Billing went in after the pipeline was already running, which meant instrumenting an operation that had never been asked to count itself. Retrofitting it was harder than building it in would have been: a generation can fail part-way, retry, or be cancelled, and each of those had to be decided on after the fact rather than designed for. It works, and I would not do it in that order again — the metering is the product's price, and a price added last is a price you are reverse-engineering from code that was written without one.",
      },
    ],
    headlines: {
      constraints: "What a per-user model costs before it earns",
      tradeoffs: "Where quality beat instant",
      build: "Train, then generate",
      result: "What Muterpe measured",
    },
    metricsNote:
      "Users and revenue are platform and billing records. The ~40% is perceived speed — time to first visible result once prompt shaping and streaming went in, against the first release — and not generation throughput, which did not change at all; the model is the same one, asked the same thing. Uptime is the rolling twelve-month figure from monitoring.",
    metrics: [
      { value: "200+", caption: "Users", note: "* self-serve signup" },
      { value: "$5K+", caption: "Revenue", note: "* usage-based" },
      { value: "99%", caption: "Uptime", note: "* rolling 12 months" },
      // Keeps the two qualifiers the write-up above states: it is perceived
      // speed, from streaming, and it is approximate. "Faster generation" flat
      // was a different and larger claim than the one that was measured.
      { value: "~40%", caption: "Faster, perceived", note: "* streaming, vs. first release" },
    ],
    reflection:
      "Usage-based billing went in late, and retrofitting metering onto a pipeline that was already running cost more than building it in from the start would have. I’d meter first and price second next time.",
  },
  {
    slug: "volumize",
    name: "Volumize",
    accentWord: "Volumize",
    tagline: "Telehealth E-Commerce Platform",
    summary:
      "A telehealth commerce platform for hair-loss treatment — medical intake, doctor approval, prescriptions, payments, despatch and subscriptions as one lifecycle across two apps. I built that lifecycle end to end, from the questionnaire a patient fills in to the despatch label that goes out two weeks early.",
    role: "Full-Stack Engineer",
    timeline: "Feb 2026 – Present",
    status: "Live",
    liveUrl: "https://volumize.co.uk",
    liveLabel: "volumize.co.uk",
    stack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "MongoDB",
      "Mongoose",
      "Socket.IO",
      "Stripe",
      "Royal Mail API",
      "AWS S3",
      "Turborepo",
      "RAG",
      "LLM",
      "Sentry",
    ],
    /*
     * Outcomes, not repository statistics. This used to lead with route-file
     * counts and a dependency-audit score — true, but they describe the shape
     * of the codebase rather than anything the business got. These are what the
     * platform actually changed once it was running.
     */
    indexMetrics: ["250+ subscriptions", "£31K+ revenue", "4 back-office roles"],
    image: img.volumize,
    alt: "Volumize telehealth commerce dashboard",
    problemHeadline: "Intake and checkout live in different systems",
    problem:
      "A hair-loss treatment journey usually runs across disconnected tools. Medical intake sits apart from the purchase flow, clinical approval and prescription handoff are manual, and order, subscription, and refund operations are scattered — which makes payments hard to reconcile and leaves nobody with a view of the whole journey.",
    context: [
      {
        k: "OWNED",
        v: "The lifecycle end to end: intake and the RAG recommendation, checkout and subscriptions, despatch, the role-based back office, monitoring and the content admin",
      },
      { k: "ROLES", v: "Four in one back office — admin · pharmacist · doctor · marketing" },
      {
        k: "NOT MINE",
        v: "The clinical decision and the dispensing — prescribing is done by the clinicians, fulfilment by a GPhC-registered pharmacy",
      },
      { k: "PRODUCT", v: "£19/mo base on 3- and 6-month courses, despatched a cycle ahead" },
      { k: "SURFACES", v: "A customer app and an operational back office over three shared packages" },
    ],
    constraints: [
      {
        title: "A missed dose is the failure that matters",
        body: "This is a treatment where stopping regresses the result — the FAQ says so in the company's own words. So the one thing I could not let the system do is let a subscriber run out between cycles. That single requirement drove more of my architecture than the commerce did: it is why despatch runs early, why retries exist, and why the order state machine refuses to go backwards.",
      },
      {
        title: "The AI cannot be the prescriber",
        body: "A model reading a medical questionnaire and recommending a treatment is useful. A model issuing a prescription is a regulated act it is not allowed to perform. Every design here had to keep a clinician in the path without making them a bottleneck who reads raw form answers cold.",
      },
      {
        title: "Enough users that failures are not theoretical",
        body: "At this volume something is always mid-flight — an approval, a despatch, a renewal. A quiet outage is not an inconvenience; it is a batch of people whose medication does not ship. The system had to tell us it was breaking before a customer did.",
      },
    ],
    approach:
      "I put the whole lifecycle behind one architecture: a Turborepo monorepo with a customer app and an operational back office, sharing auth, data models and UI so the two surfaces cannot drift apart. Then I designed the subscription around continuity rather than around the billing date — because on a course of treatment, the calendar the customer cares about is not when they are charged, it is when the medicine runs out.",
    tradeoffs: [
      {
        decision: "Despatch the next cycle two weeks before the current one runs out",
        instead: "Ship on the renewal date, the way a subscription normally works",
        cost: "Stock is in flight earlier and there is more of it out at any moment, and a cancellation mid-cycle can land after a despatch has already gone.",
        bought: "Nobody misses a dose. On a treatment whose benefits regress once it stops, a two-day gap in the post is not a logistics inconvenience — it is the customer losing the result they are paying for, and then leaving. Shipping early converts a delivery risk into a small inventory cost.",
      },
      {
        decision: "Retry despatch repeatedly rather than failing to a human",
        instead: "Fail the job on the first error and raise it for someone to handle",
        cost: "Retries have to be idempotent or they duplicate an order, which is a real cost in physical goods rather than a duplicated row.",
        bought: "A transient Royal Mail or pharmacy error stops being a missed delivery. Most of these failures resolve on their own within minutes; escalating each one to a person is how a queue becomes a backlog overnight.",
      },
      {
        decision: "The questionnaire recommends, a clinician decides",
        instead: "Let the pipeline issue the plan directly for a doctor to rubber-stamp",
        cost: "Throughput is bounded by clinician time, and the AI's work is advisory rather than final.",
        bought: "It is lawful, and it is safe. The prescriber sees a suggested plan with its reasoning instead of raw form answers, which is what actually made review faster — the speed came from better input to the human, not from removing them.",
      },
      {
        decision: "Health-check services and error tracking from the start",
        instead: "Rely on customer reports and server logs, which is free",
        cost: "More services to run, and alert thresholds that need tuning or they train you to ignore them.",
        bought: "We hear about an outage before a patient does. In a business that ships medicine on a schedule, the gap between something breaking and someone noticing is measured in missed deliveries.",
      },
    ],
    decisions: [
      "Split the product into a customer app and an operational back office over three shared packages — auth, db, ui — so an order means the same thing on both sides of the platform.",
      "Issued separate session tokens for customers and staff rather than one shared trust boundary, keeping the blast radius of a leaked session inside a single surface.",
      "Modelled the order lifecycle as explicit statuses and transitions, so questionnaire, clinical review, prescription and fulfilment are one traceable pipeline rather than four systems agreeing by convention.",
      "Kept refunds executing against the same Stripe environment as the original charge, so payment operations reconcile instead of drifting.",
      "Integrated the Royal Mail API so despatch generates the label and writes tracking back onto the order, taking an approved prescription to shipped without anyone handling it.",
    ],
    diagram: {
      src: "/projects/volumize-lifecycle.svg",
      alt: "Volumize order lifecycle: signup, medical questionnaire and checkout, then doctor review branching to either prescription, pharmacy handoff and Royal Mail despatch feeding subscription renewal, or rejection and refund",
      caption: "* ONE ORDER, END TO END",
    },
    build: [
      {
        title: "Two apps, one domain layer",
        body: "The customer app and the back office are separate deployments over shared auth, database, and UI packages. Fifteen Mongoose models live in one place, so an order means the same thing on both sides of the platform.",
      },
      {
        title: "Intake to delivery, as one pipeline",
        body: "Signup leads into a medical questionnaire, then checkout, then doctor review. Approval generates a prescription PDF and hands off to the pharmacy; rejection stops the order. Despatch runs through the Royal Mail API — labels generated and tracking written straight back onto the order — so nobody is creating labels by hand. Delivery rolls into the subscription renewal cycle, and refunds are a modelled branch rather than an afterthought.",
      },
      {
        title: "A questionnaire that recommends, not just records",
        body: "The medical intake is not a form that files answers away for a doctor to read cold. Answers go through a retrieval-augmented pipeline over the treatment material — the ingredients, their indications, the contraindications — and it comes back with a suggested plan and the reasoning for it. That suggestion is a starting point for the clinician, never a decision: the prescriber still reviews and still approves, because a model that recommends a prescription without a human in the path is a regulatory problem, not a feature.",
      },
      {
        title: "Four roles, one back office",
        body: "Admin, pharmacist, doctor and marketing all work in the same operational app and must not see the same thing. A doctor needs the clinical questionnaire and the approval decision; a pharmacist needs the approved prescription and the despatch queue; marketing needs the content and the campaign surfaces and no patient data at all. I enforce that on the server, per route, rather than by hiding buttons — in a system carrying medical answers and prescriptions the interface is not the security boundary, and a hidden button is a URL somebody can still type.",
      },
      {
        title: "Content the marketing team owns",
        body: "The blog and its posts are managed from the same admin, so campaign content ships without a deploy and without an engineer. It is the least clinically interesting part of the platform and one of the most requested: the alternative is a marketing team filing tickets to change a paragraph.",
      },
      {
        title: "Security hardening pass",
        body: "A phased dependency remediation — non-breaking fixes first, breaking upgrades second — prioritising routing, middleware, email transport, and the parsing and network stack. Next.js moved to 16.3.0 and Nodemailer to 9.0.4, clearing every high and moderate finding across a 1,127-package graph. Query optimisation and edge caching took 1.8s off page load and 35% off API response time in the same pass.",
      },
    ],
    metrics: [
      /*
       * Revenue first, then the two operational numbers that produced it. The
       * build statistics that used to sit here — 94 route files, a 97% cut in
       * vulnerabilities, an audit score of 99 — are still true and still
       * described in the build blocks above; they are just not what a clinic
       * or a client is asking about. The saved admin hours and the page-load
       * improvement moved into those blocks for the same reason.
       */
      {
        value: "250+",
        caption: "Live subscriptions",
        note: "* £19/mo base, 3- and 6-month plans",
      },
      { value: "£31K+", caption: "Subscription revenue", note: "* booked across those plans" },
      {
        value: "-45%",
        caption: "Approval turnaround",
        note: "* review to prescription, vs. manual handoff",
      },
      {
        value: "-85%",
        caption: "Order despatch time",
        note: "* after Royal Mail label + tracking sync",
      },
      { value: "4", caption: "Back-office roles", note: "* admin · pharmacist · doctor · marketing" },
    ],
    headlines: {
      constraints: "What medicine on a schedule rules out",
      tradeoffs: "Where continuity beat convention",
      build: "The lifecycle, part by part",
      result: "What Volumize measured",
    },
    metricsNote:
      "Subscriptions and revenue are booked figures from the platform. The two percentages are before-and-after on the same flow rather than controlled measurements, and each compares a specific pair: −45% is clinician review time once the questionnaire started arriving with a suggested plan and its reasoning, against reading raw form answers cold; −85% is despatch time through the Royal Mail integration, against generating labels and copying tracking by hand. Both are averages over the orders that ran through each path, not a guarantee on any single order.",
    reflection:
      "The security work was reactive — 34 findings had already accumulated before anyone went looking. The fix was a one-off cycle when it should have been a gate: audit thresholds in CI, so the graph never drifts that far again. Cutting vulnerabilities by 97% reads well, but not having needed to reads better.",
  },
  {
    slug: "wisdomup",
    name: "WisdomUp",
    accentWord: "WisdomUp",
    tagline: "Multi-Service E-Commerce Platform",
    summary:
      "A three-service commerce platform — storefront, transactional API and CMS admin — that I built around a checkout designed to survive its own edge cases rather than its happy path.",
    role: "Full-Stack Product Engineer",
    timeline: "2026 – Present",
    status: "In development",
    inDevelopment: true,
    stack: [
      "Next.js",
      "TypeScript",
      "Express 5",
      "MongoDB",
      "Payload CMS",
      "Stripe",
      "Redux Toolkit",
      "RTK Query",
      "Zod",
    ],
    indexMetrics: ["3 services", "8-layer payment guard", "14 settlement tests"],
    image: img.wisdomup,
    alt: "WisdomUp storefront and admin dashboard",
    problemHeadline: "Checkout breaks in the edge cases",
    problem:
      "E-commerce builds tend to fail in the same three places. Content changes need a developer, so campaigns wait on deploys. Payment edge cases — duplicate webhooks, events arriving out of order, amounts that do not match — turn into real financial risk. And a monolith makes both problems harder to fix safely.",
    context: [
      { k: "ROLE", v: "Full-stack product engineer across all three services" },
      {
        k: "OWNED",
        v: "Storefront · Express transactional API · Payload CMS admin · the settlement path that runs between them",
      },
      { k: "SURFACES", v: "Three independently deployable services over one shared MongoDB" },
      {
        k: "SCOPE",
        v: "Catalog derived from host and market, so one codebase serves a local and a global storefront",
      },
      {
        k: "STATUS",
        v: "In development — the payment path is hardened and tested, and has not yet carried production traffic",
      },
    ],
    constraints: [
      {
        title: "The money settles once; the events describing it do not",
        body: "Stripe confirms a payment a single time and then tells you about it repeatedly — duplicated, delayed, and occasionally in the wrong order. Nothing in the design was allowed to assume an event is the first time it has been seen, because in a payment system that assumption is not a bug that shows up in a log, it is a customer charged twice or an order that ships against a payment that failed.",
      },
      {
        title: "A campaign cannot wait for a release",
        body: "Merchandising changes — a banner, a testimonial, an FAQ, a hero — arrive faster than deploys do, and the usual outcome is either a queue of trivial pull requests or copy that is quietly out of date. Content had to be editable by the people who write it, which meant the page could no longer assume any field it renders is actually there.",
      },
      {
        title: "Nothing here has production traffic to check it against",
        body: "The reliability work is tested rather than observed, and that is a real limit on what I can claim here. Guard layers and settlement tests prove the logic does what I wrote it to do; they do not prove the assumptions behind it survive real payment traffic, and those are not the same thing. I would rather say that than present a tested system as a proven one.",
      },
    ],
    approach:
      "I separated the three concerns into independently deployable services, then treated settlement as a distributed-systems problem rather than a happy path. The whole payment layer is written on one assumption I decided to take seriously: events arrive twice, late, or out of order — so the order state machine refuses to go backwards, and every write that touches money can be replayed without doing anything a second time.",
    tradeoffs: [
      {
        decision: "Settle down two independent paths",
        instead: "Trust the webhook alone, which is what Stripe's own documentation recommends and is one code path instead of two",
        cost: "Two writers reach the same order, so every guard has to be idempotent and the two paths have to agree about what has already happened. It is strictly more to get right than one path would be.",
        bought: "Neither failure mode can lose an order, which is why I took the more expensive path. A browser that dies after payment is covered by the webhook; a webhook that is delayed or dropped is covered by the confirmation the client already made. The single-path version is correct until the one time it is not, and that time is somebody's money — I would rather maintain two paths than explain that call.",
      },
      {
        decision: "Order status only moves forward",
        instead: "Apply whatever the latest event says, which is the obvious reading of an event stream",
        cost: "Legitimate reversals — a refund, a cancellation — need their own explicit transition rather than simply setting the status back. The state machine has to be extended rather than assigned to.",
        bought: "A stale event cannot un-ship an order. Out-of-order delivery stops being a correctness problem and becomes a no-op: an event describing a state the order has already passed is discarded rather than applied, which is the difference between handling reordering and hoping it does not happen.",
      },
      {
        decision: "Three services over one shared database",
        instead: "A database per service, which is what service separation is normally taken to mean",
        cost: "This is not real isolation. The services share a schema, so a model change is coordinated across three codebases and one of them can still write something another did not expect.",
        bought: "No distributed transaction anywhere near a checkout. A database per service would have put eventual consistency between taking a payment and recording an order, and my honest answer is that separate deployables with bounded write ownership buy most of the benefit at none of that cost. I would rather ship the version I can reason about than the one that matches the diagram in the article.",
      },
      {
        decision: "Content is data the CMS owns, not components the repository owns",
        instead: "Hard-code the sections and ship a release when marketing wants a change",
        cost: "Every rendered field is now something that might be absent, so the storefront needs typed contracts and defensive rendering throughout — and a content editor can technically break a page in a way a compiler will not catch.",
        bought: "A campaign is an edit rather than a deploy. Eleven admin collections plus navigation and site settings as editable globals mean the release cadence of the storefront stops being the release cadence of its copy, which is the difference between a marketing team that ships and one that files tickets.",
      },
    ],
    decisions: [
      "Split into a storefront, an Express transactional API and a Payload CMS admin, each deployable on its own with bounded ownership over a shared database.",
      "Settled payments down two independent paths — immediate confirmation after client success, and a webhook fallback — so a dropped browser never loses an order.",
      "Guarded settlement with signature verification, ownership and amount checks, idempotency keys, a unique transaction index and replay protection, then made order status monotonic so a stale event is discarded rather than applied.",
      "Derived catalog scope from host and market and enforced it again at checkout, so a local product cannot be bought through the wrong storefront.",
    ],
    diagram: {
      src: "/projects/wisdomup-settlement.svg",
      alt: "WisdomUp architecture: a storefront, an Express transactional API and a Payload CMS admin over one shared database, with payment settled down two independent paths behind eight guard layers and an order status that only moves forward",
      caption: "* THREE SERVICES + DUAL SETTLEMENT",
    },
    build: [
      {
        title: "Two paths to settled",
        body: "The client confirms with Stripe and the backend records it immediately. The webhook then arrives and reconciles — verifying signature, checking the amount and owner, deduplicating on a unique transaction index, and refusing any event that would move the order backwards. Fourteen tests cover that logic specifically.",
      },
      {
        title: "Merchandising without a deploy",
        body: "Hero, banners, feature bars, FAQs, and testimonials are CMS collections, not components. Eleven admin collections plus site settings and navigation as editable globals mean a campaign change is an edit, not a release — with CSV product import for bulk catalog work.",
      },
      {
        title: "Storefront surface",
        body: "Listing and detail flows with category filtering and search, cart and wishlist, guest checkout with resumable session state, promo codes validated server-side for both eligibility and discount, and reviews rendered moderation-aware. Guest checkout is the one worth naming: session state survives a closed tab, because the most common way to lose an order is not a payment failure, it is someone leaving to check something and coming back to an empty cart.",
      },
    ],
    metrics: [
      { value: "3", caption: "Deployable services", note: "* storefront · API · CMS" },
      { value: "8", caption: "Payment guard layers", note: "* signature to state machine" },
      { value: "14", caption: "Settlement tests passing", note: "* confirmation logic" },
      {
        value: "2",
        caption: "Independent paths to settled",
        note: "* client confirmation · webhook fallback",
      },
    ],
    headlines: {
      constraints: "What a payment system has to assume",
      tradeoffs: "Where correctness beat the simpler path",
      build: "The three services",
      result: "What is built — and what is not yet observed",
    },
    metricsNote:
      "None of these is a production reading, because there is no production traffic yet. They are counts of what exists, checked against the codebase: three deployables, eight guards on the settlement path, fourteen passing tests over the confirmation logic, two independent routes to a settled order. The tests passing proves the logic does what I wrote it to do. It does not prove the assumptions behind it hold, and the reflection below is about exactly that gap.",
    reflection:
      "Everything measurable here is about the build, not the business. The payment layer is hardened and tested, but checkout success rate, reconciliation accuracy, and promo conversion are still targets rather than readings — I set them without shipping the instrumentation to answer them. Reliability engineering you cannot observe in production is a hypothesis, and I would wire the funnel telemetry before adding another feature.",
  },
  {
    slug: "alfa",
    name: "Alfa",
    accentWord: "Alfa",
    tagline: "Multi-Role Fintech Platform",
    summary:
      "A role-aware fintech platform serving personal, business and admin journeys from one architecture — onboarding, transfers, bill splitting, top-ups, currency conversion, scheduled payments and card management over Python microservices. I own the session and authorisation model, onboarding and verification, document handling, and the client data layer the whole product reads through.",
    role: "Full-Stack Engineer — Python microservices & Next.js client",
    timeline: "Feb 2026 – Present",
    status: "In development",
    inDevelopment: true,
    stack: [
      "Python",
      "FastAPI",
      "Supabase",
      "GraphQL",
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Redux Toolkit",
      "RTK Query",
      "Zod",
      "Tailwind v4",
      "AWS S3",
    ],
    /*
     * Services delivered and interfaces designed, rather than the shape of the
     * repository. "4 route groups" described a directory layout; these describe
     * what the platform does and what was built to make it do it.
     */
    indexMetrics: ["6 isolated capabilities", "2 authorisation layers", "4 measures instrumented"],
    image: img.alfa,
    alt: "Alfa fintech dashboard",
    problemHeadline: "Acting as the wrong account is not a UI bug",
    problem:
      "A person can hold a personal account and a business account at the same time, arrive with neither selected, and be part-way through verification on one of them. Most applications treat that as a navigation question and let each page work out where the user should be. In a product that moves money it is not a navigation question: a transfer initiated while the app is guessing leaves the wrong balance, and a payment surface rendered before verification finishes lets someone move funds they are not yet cleared to move. The failure does not look like a broken route — it looks like an unauthorised debit, and it is found by the customer.",
    context: [
      { k: "ROLE", v: "Full-stack engineer — the FastAPI services and the Next.js client on top of them" },
      {
        k: "OWNED",
        v: "Session and authorisation model · onboarding and verification · document handling · the client data layer",
      },
      {
        k: "NOT MINE",
        v: "The banking rails — issuing, funding and exchange rates sit behind providers, and the regulated permissions are the operator's",
      },
      { k: "SURFACES", v: "Three journeys out of one architecture — personal, business and admin" },
      {
        k: "STATUS",
        v: "In development and pre-traffic, which is why the measures below are instrumented rather than reported",
      },
    ],
    constraints: [
      {
        title: "Verification gates money, not features",
        body: "Onboarding is not a form to complete at leisure; until identity checks pass, the account is not cleared to move funds. That makes onboarding completeness a condition on rendering payment surfaces at all, rather than a banner asking someone to finish later — and it has to hold for a personal account and a business account independently, because the same person can be verified on one and not the other.",
      },
      {
        title: "Identity documents are the most sensitive thing here",
        body: "Verification means passports, incorporation papers and proof of address. That is the data with the worst consequences if it leaks, so I could never let it go straight from the browser to storage with a credential the client can see — however much simpler that would have been, and it would have been considerably simpler.",
      },
      {
        title: "A capability failing must not look like the bank being down",
        body: "Currency conversion depends on a rate provider, cards on an issuer, top-ups on a funding rail. Each has its own reasons to be unavailable. If any one of them takes the platform down with it, a customer who only wanted to check a balance sees an outage — and in a money product that is the moment trust is lost.",
      },
    ],
    tradeoffs: [
      {
        decision: "Resolve identity before a money surface exists",
        instead: "Render the dashboard and let each page check what it is allowed to show",
        cost: "A resolution step before the first meaningful paint, and one guard that has to be right for the whole application rather than many small checks that are individually easy to reason about.",
        bought: "There is no window in which a transfer form is on screen for an account the system has not confirmed the user selected and cleared. The failure this removes is not a wrong redirect — it is money leaving the wrong balance, which is the kind of bug a customer reports rather than a test catches.",
      },
      {
        decision: "Authorise twice — at the route, and at the row",
        instead: "Trust the route guard, since the client cannot reach the data without passing it",
        cost: "Rules exist in two places and both have to be maintained, which is real duplication rather than the elegant single source of truth.",
        bought: "A mistake in application code cannot expose another account's transactions. Row-level rules sit next to the data and apply whatever calls it, which is the difference between an authorisation model and an authorisation convention.",
      },
      {
        decision: "One service per financial capability",
        instead: "One payments service, which is far less to run for a team this size",
        cost: "Six deployables to operate, six sets of logs, and cross-capability changes that need more than one release.",
        bought: "An incident stays inside the capability it happened in. A rate provider going down degrades currency conversion and leaves transfers, balances and cards untouched — so the customer sees one feature unavailable rather than concluding the bank is down.",
      },
      {
        decision: "Identity documents move through the server",
        instead: "Upload straight from the browser to object storage with a client-held credential",
        cost: "Every file crosses the application on its way in, and route handlers have to deal with size and streaming rather than handing that to the storage provider.",
        bought: "No credential that can reach the verification bucket exists in the browser. Passports and incorporation papers are the worst thing in this product to leak, and the simpler upload path is only simpler until it is not.",
      },
    ],
    approach:
      "I treat identity as something the system resolves before it renders anything that can move money, and each financial capability as something that can fail without taking the others down with it. On the client, middleware does one cheap thing at the edge — is there a token at all — and every conditional question (which account, which role, is verification complete) is answered once against a single bootstrapped user object. No screen is allowed to infer it. On the server, transfers, currency conversion, top-ups, bill splitting, recurring payments and cards are separate FastAPI services behind a GraphQL layer, so an incident stays scoped to the capability it happened in. I enforce authorisation twice on purpose: at the route, and again as row-level rules sitting next to the data.",
    decisions: [
      "Kept edge middleware to one cheap question: is there a token at all.",
      "Answered role, session and verification once, in a single guard against bootstrapped state, rather than per screen.",
      "Put 10+ GraphQL APIs in front of the services, so a screen asks for what it needs in one request instead of a REST fan-out that differs per role.",
      "Created one RTK Query base API and had seven domains inject their own endpoints into it — one reducer, one middleware, one cache.",
      "Instrumented the four measures a payments platform is actually judged on — authorisation rate, transfer p95, reconciliation break rate, KYC completion — before there was traffic to run through them.",
    ],
    diagram: {
      src: "/projects/alfa-services.svg",
      alt: "Alfa architecture: an edge token gate and a single client-side guard resolve role and session once per visit, one RTK Query base API serves seven domains, and 10+ GraphQL APIs sit in front of six independently deployable FastAPI services over Supabase",
      caption: "* AUTH + SERVICE TOPOLOGY",
    },
    build: [
      {
        title: "Hybrid auth model",
        body: "Login optionally passes through 2FA before an access token lands in a cookie. A bootstrap provider then fetches the user once and hands Redux the session. From there the guard resolves one of four outcomes — admin area, dashboard, onboarding, or an account selector when someone holds both account types and has not picked a session.",
      },
      {
        title: "One API, seven domains",
        body: "Rather than a slice per feature, a single baseApi is created once and each domain injects its own endpoints: auth, business, cards, transactions, schedules, wallet, admin. Adding an endpoint means touching one file and getting caching, tag invalidation, and generated hooks for free.",
      },
      {
        title: "Verification, and the documents it runs on",
        body: "Onboarding is routed by account type, because verifying a person and verifying a company ask for different things and fail in different places — so an incomplete business journey and an incomplete personal one are separate paths rather than one page branching inside itself. The guard treats an unfinished journey as a reason to redirect rather than a banner to display, which is what keeps a payment surface from rendering for an account that is not yet cleared. The documents themselves — identity, proof of address, incorporation papers — are uploaded and deleted through Next.js route handlers using the AWS SDK server-side, so no credential capable of touching that bucket is ever present in the browser. Direct-from-client upload would have been less code and a worse idea, and it is the one place in this build where I deliberately chose the heavier option.",
      },
      {
        title: "Four route groups, one set of rules",
        body: "The app is partitioned by what a person is allowed to be doing rather than by feature: auth, onboarding, dashboard and admin. Zod schemas are shared across those groups, so a field validated at signup is validated identically when it is edited a year later — the usual failure being two definitions of the same rule that drift apart until one of them lets something through.",
      },
      {
        title: "Money movement surfaces",
        body: "Transfers for personal and business contexts, payment requests, calendar-driven scheduled payments, transaction history, and card issuing and assignment — each built from shared layout shells and form primitives so a new dashboard screen starts from composition rather than scratch.",
      },
      {
        title: "The four numbers this gets judged on",
        body: "A payments platform is not judged on how much of it exists. It is judged on four readings, and I instrumented all four before there was traffic to produce them. Authorisation rate is the share of attempted payments that clear, and it is the one watched first: a drop of a point is invisible in an error log and enormous in revenue, and it catches an issuer problem, a rail problem and a bug in my own retry logic with the same signal.",
      },
      {
        title: "p95, not the average",
        body: "Transfer latency is measured at the 95th percentile, from the request entering the transfer service to the ledger entry being written. The mean hides exactly the tail that matters — the slow requests are where someone abandons a payment and calls support, and an average is very good at making a hundred of those disappear behind ten thousand fast ones. Reconciliation break rate sits beside it: the share of movements where my record and the provider's disagree at end of day. That one has to trend to zero rather than to something tolerable, because every break is money sitting somewhere other than where the system says it is.",
      },
      {
        title: "Verification, measured per step",
        body: "KYC completion is measured at each onboarding step rather than as one funnel number, because verification gates funding rather than features. An account that stalls on proof of address is not a conversion problem to optimise later — it is a customer who cannot use the product, and a single completion percentage tells you that happened without telling you where. None of these four has a production reading yet; Alfa is pre-traffic, and a figure printed here would be one I invented. What exists is the emission at each point, the thresholds, and the decision about which of them is allowed to wake someone up.",
      },
    ],
    metrics: [
      /*
       * Controls, which is what this domain measures. A payments platform is
       * judged on what it makes impossible — funds moving from an account the
       * user did not select, one account reading another's rows, a rate
       * provider taking the whole product down — not on how much was built.
       * The four figures a fintech publishes alongside these — authorisation
       * rate, p95 on the transfer path, reconciliation break rate and KYC
       * completion — need production traffic to mean anything. The last tile
       * therefore counts the instrumentation, and the build block above defines
       * each measure and its threshold. Printing a value would be inventing one.
       */
      {
        value: "0",
        caption: "Money surfaces before identity resolves",
        note: "* the guard settles the account, then the screen exists",
      },
      {
        value: "2",
        caption: "Layers authorising a read",
        note: "* route guard, and row-level rules at the data",
      },
      {
        value: "6",
        caption: "Capabilities that fail alone",
        note: "* an FX outage is not a transfers outage",
      },
      {
        value: "4",
        caption: "Service levels instrumented",
        note: "* auth rate · transfer p95 · recon breaks · KYC completion",
      },
    ],
    headlines: {
      constraints: "What moving money rules out",
      tradeoffs: "Where safety beat simplicity",
      build: "What Alfa is made of",
      result: "What Alfa guarantees — and what it will measure",
    },
    metricsNote:
      "None of these is a production reading, and the heading above says so deliberately. Alfa has no live traffic. The first three are properties of the architecture rather than measurements of behaviour — they are verifiable by reading the code, not by watching it run — and the fourth counts instrumentation, not output. The four measures that will actually judge this platform are defined in the build section above, and they will carry values when there is traffic to produce them. Until then I would rather show you what the system makes impossible than a number I made up.",
    reflection:
      "The architecture is sound but under-tested for what it is. Money movement and auth are exactly the paths that deserve integration and end-to-end coverage, and right now correctness rests on the guard logic being right rather than on anything proving it. That is the next thing I would build, before analytics on onboarding drop-off or feature flags for staged rollout.",
  }
];

/**
 * Reading order, and the numbering that comes with it.
 *
 * The case-study page shows two numerals for the same project: a position
 * counter in the sticky bar ([02 / 06]) and the authored [CASE STUDY nn] tag.
 * Those were separate values — declaration order for one, a hand-written
 * `index` field for the other — and four of the six disagreed. Deriving the
 * index from this list makes them the same number by construction, and makes
 * prev/next walk the projects in the order the site actually presents them.
 */
const ORDER = ["carder", "volumize", "golegal", "alfa", "wisdomup", "muterpe"] as const;

export const projects: Project[] = ORDER.map((slug, i) => {
  const project = authored.find((p) => p.slug === slug);
  if (!project) throw new Error(`ORDER lists a slug with no project: ${slug}`);
  return { ...project, index: String(i + 1).padStart(2, "0") };
});

/*
 * The guard above catches a slug with no project. This catches the direction
 * that fails quietly: a project added to `authored` and forgotten here would
 * simply vanish — no route from generateStaticParams, no card on the index, no
 * entry in the sitemap, and nothing anywhere to say so.
 */
if (projects.length !== authored.length) {
  const missing = authored.map((p) => p.slug).filter((slug) => !ORDER.includes(slug as never));
  throw new Error(`Projects missing from ORDER: ${missing.join(", ")}`);
}

const bySlug = Object.fromEntries(projects.map((p) => [p.slug, p])) as Record<string, Project>;

/**
 * The four the index leads with, in the order it leads with them.
 *
 * `ORDER` above is *routing* order — it feeds `generateStaticParams`, the
 * case-study numbering and prev/next, so it stays put. This is
 * presentation order, and the two are allowed to differ: WisdomUp and Muterpe
 * still have full case studies, they just no longer earn a pinned card on the
 * index. They surface through `otherWork` instead, which links straight at
 * those same pages.
 */
export const featuredProjects: Project[] = ["carder", "volumize", "golegal", "alfa"].map(
  (slug) => bySlug[slug],
);

export type OtherWork = {
  name: string;
  tagline: string;
  /** One line. This list is an index, not a second case-study section. */
  note: string;
  stack: string[];
  status: string;
  href: string;
  /** Case studies link inward; everything else opens in a new tab. */
  external?: boolean;
  hrefLabel: string;
};

/**
 * Shipped work that isn't the argument the index is making. Two of these have
 * full case studies and point at them; the third is a live site and points at
 * itself.
 */
export const otherWork: OtherWork[] = [
  {
    name: "WisdomUp",
    tagline: "Multi-Service E-Commerce Platform",
    note: "Storefront, transactional API, and CMS admin as three deployable services, with settlement guarded down two paths so a dropped browser never loses an order.",
    stack: ["Next.js", "Express 5", "MongoDB", "Payload CMS", "Stripe"],
    status: "In development",
    href: "/work/wisdomup",
    hrefLabel: "Read the case study",
  },
  {
    name: "LightspeedGo",
    tagline: "Logistics & Delivery Platform",
    note: "Marketing and booking surface for a courier operation — live, and the front door for the dispatch flow behind it.",
    stack: ["Next.js", "TypeScript", "Tailwind"],
    status: "Live",
    href: "https://lightspeedgo.com",
    external: true,
    hrefLabel: "lightspeedgo.com",
  },
  {
    name: "Muterpe",
    tagline: "AI Image Generation SaaS",
    note: "Per-user model training and generation on Fal.ai, monetized usage-based, with an async queue so a baking model never blocks the UI.",
    stack: ["Next.js", "PostgreSQL", "Fal.ai", "OpenAI", "AWS S3"],
    status: "Live, monetized",
    href: "/work/muterpe",
    hrefLabel: "Read the case study",
  },
];

/** One node of the agent's state machine, as the index replays it. */
export type TraceStep = {
  id: string;
  label: string;
  /** What the node actually emitted — shown as the span's result line. */
  detail: string;
  ms: number;
  tokens?: number;
  /** The human-approval interrupt. The replay stops here until someone taps. */
  gate?: boolean;
};

/**
 * mailagent — in build, not shipped, and listed that way on purpose.
 *
 * The interesting claim here isn't "an LLM reads your email", it's the
 * engineering around it: a scoring harness that existed before the extractor,
 * a retrieval comparison whose losing arm shipped disabled, and cost accounting
 * that records an unpriced call as NULL rather than lying with a zero. The
 * index replays the graph instead of describing it.
 */
export const comingSoon = {
  name: "mailagent",
  tagline: "Human-in-the-Loop Scheduling Agent",
  status: "In build",
  summary:
    "Reads Gmail, spots meeting requests, extracts the details, checks the calendar for conflicts, and sends a Telegram card with Confirm / Edit / Cancel. Nothing touches the calendar without a human tap.",
  stack: [
    "Python 3.12",
    "FastAPI",
    "LangGraph",
    "Gemini",
    "Postgres + pgvector",
    "Gmail & Calendar APIs",
    "Telegram Bot API",
    "Next.js",
  ],
  trace: [
    {
      id: "classify",
      label: "classify",
      detail: 'intent="schedule_meeting" · confidence 0.94',
      ms: 412,
      tokens: 318,
    },
    {
      id: "extract",
      label: "extract",
      detail: 'title="Design sync" · Thu 14:00–14:45 GMT · 3 attendees',
      ms: 1180,
      tokens: 902,
    },
    {
      id: "retrieve",
      label: "retrieve",
      detail: "pgvector · 5 prior threads · hit@5 1.00 (fusion off)",
      ms: 96,
    },
    {
      id: "conflict_check",
      label: "conflict_check",
      detail: "1 overlap — “1:1 · Ali” Thu 14:30. Proposing 15:00.",
      ms: 240,
    },
    {
      id: "human_approval",
      label: "human_approval",
      detail: "interrupt — awaiting Telegram callback",
      ms: 0,
      gate: true,
    },
    {
      id: "act",
      label: "act",
      detail: "calendar.events.insert · 200 · reply drafted",
      ms: 588,
    },
  ] satisfies TraceStep[],
  /** Numbers that came out of the harness, not out of a pitch. */
  evidence: [
    { value: "92.9%", caption: "Exact-match extraction", note: "* 14 hand-labelled fixtures" },
    { value: "100%", caption: "Retrieval hit@5", note: "* vector-only, 29 queries" },
    { value: "NULL", caption: "Unpriced call cost", note: "* never recorded as 0" },
    { value: "OFF", caption: "RRF fusion, shipped", note: "* built, measured, lost" },
  ],
  /**
   * The most distinctive part of the write-up. Four real production bugs, kept
   * in the reader's view rather than buried in a repo — a portfolio that only
   * lists wins is a portfolio nobody believes.
   */
  broke: [
    {
      title: "Auth bypass",
      body: "An empty Telegram secret matched an empty header, so an unsigned request authenticated cleanly. Fixed by refusing to start when the secret is unset.",
    },
    {
      title: "Silent batch collapse",
      body: "The Gemini SDK quietly folded an embedding batch, returning fewer vectors than inputs with no error. Caught by a length assertion that should have been there first.",
    },
    {
      title: "tsquery AND vs OR",
      body: "A Postgres full-text query built with the wrong operator flipped a benchmark result. The BM25 arm looked worse than it was for two days.",
    },
    {
      title: "A confident wrong answer",
      body: "An A/B run picked a winner on one pass. Repeating it exposed fixture-level variance wide enough to swallow the difference — the result was noise wearing a decision.",
    },
  ],
} as const;

export const getProject = (slug?: string) => projects.find((p) => p.slug === slug);

export const projectNeighbours = (slug: string) => {
  const i = projects.findIndex((p) => p.slug === slug);
  if (i < 0) return { prev: undefined, next: undefined, position: 0 };
  return {
    prev: projects[(i - 1 + projects.length) % projects.length],
    next: projects[(i + 1) % projects.length],
    position: i + 1,
  };
};
