/**
 * Project content.
 *
 * IMAGES: the six screenshots below are placeholders generated into
 * `public/projects/`. Drop your real files into that folder and change the
 * paths here — that is the only edit needed (e.g. "/projects/carder.jpg").
 */
const img = {
  carder: "/projects/carder-hero.png",
  carderMedia: "/projects/carder-media.png",
  carderTiers: "/projects/carder-tiers.png",
  golegal: "/projects/golegal-editor.webp",
  muterpe: "/projects/muterpe.svg",
  alfa: "/projects/alfa.svg",
  volumize: "/projects/volumize.svg",
  wisdomup: "/projects/wisdomup.svg",
  diagram: "/projects/diagram.svg",
  terminal: "/projects/terminal.svg",
} as const;

export const projectImages = img;

export type Metric = { value: string; caption: string; note?: string };

/*
 * `image` is optional. Some of what a build is made of has no public screen to
 * show — an internal back office, a billing path — and captioning an unrelated
 * picture as that thing is worse than showing nothing. A block without an image
 * renders full width instead.
 */
export type BuildBlock = { title: string; body: string; image?: string; alt?: string };

export type Project = {
  slug: string;
  index: string;
  name: string;
  accentWord: string;
  tagline: string;
  summary: string;
  role: string;
  timeline: string;
  status: string;
  inDevelopment?: boolean;
  liveUrl?: string;
  liveLabel?: string;
  /** The URL is a login wall, not a public page. Say so before it is clicked. */
  liveGated?: boolean;
  stack: string[];
  indexMetrics: string[];
  image: string;
  alt: string;
  problem: string;
  problemHeadline: string;
  approach: string;
  decisions: string[];
  diagram?: { src: string; alt: string; caption: string };
  build: BuildBlock[];
  metrics: Metric[];
  reflection: string;

  /*
   * The three sections below are what separate an account of a job from a list
   * of tasks completed, and all three are optional so a case study can be
   * upgraded one at a time rather than all six at once.
   */

  /** Team, scale and ownership. What a reader needs before the problem means anything. */
  context?: { k: string; v: string }[];
  /**
   * What could not be done. A build with no stated constraints reads as a
   * greenfield exercise; naming them is what shows the work was real.
   */
  constraints?: { title: string; body: string }[];
  /**
   * Decisions written as decisions: what was chosen, what was rejected, what it
   * cost and what it bought. "Integrated Stripe" is a task. "Chose Stripe as
   * the source of truth over mirroring entitlements locally, and paid for it in
   * network calls" is a decision.
   */
  tradeoffs?: { decision: string; instead: string; cost: string; bought: string }[];
  /** Production failures, kept in the reader's view — the device mailagent already uses. */
  broke?: { title: string; body: string }[];
};

/*
 * The projects as written. The catalogue index is deliberately absent: it is
 * derived from ORDER below, so the number on the page and the number in the
 * counter cannot drift apart again.
 */
const authored: Omit<Project, "index">[] = [
  {
    slug: "carder",
    name: "Carder",
    accentWord: "Carder",
    tagline: "AI Mini-Site Builder",
    summary:
      "An AI site builder for small local businesses: one sentence in, a complete mini-site out in about thirty seconds, on a free tier and two paid ones. I led the backend, the data layer and the billing and media infrastructure it runs on.",
    role: "Backend & Infrastructure Lead",
    timeline: "Nov 2022 – Feb 2026",
    status: "Live",
    liveUrl: "https://carder.app",
    liveLabel: "carder.app",
    stack: ["Laravel", "Next.js", "TypeScript", "Node.js", "Express", "SQL", "Stripe", "AWS S3"],
    /*
     * No revenue figure. The public pricing is $0 / $12 / $29 with a free tier
     * most sites sit on, so any MRR number stated here would be contradicted by
     * the pricing page one click away. Users and adoption are the two claims
     * that survive being checked.
     */
    indexMetrics: ["150+ users", "+40% adoption", "3 metered tiers"],
    image: img.carder,
    alt: "Three sites generated by Carder: a bakery menu, a salon services page, and an Arabic restaurant menu in right-to-left layout",
    problemHeadline: "A list of links is not a business",
    problem:
      "A bakery in Haifa, a salon that books over WhatsApp, a clinic answering the same three questions all day. None of them are offline because they do not care; they are offline because every option asked too much — a designer, a week, a bill, or a page builder they would have to learn. The link-in-bio tools they end up with only point elsewhere: a menu PDF here, a phone number there, every button sending the visitor away from the one place they arrived. Carder's answer is to put the whole business on that link and generate it from a sentence. The engineering problem underneath is less glamorous: the thing had to bill, meter and serve those sites reliably, on a Laravel app that was already carrying paying customers.",
    context: [
      { k: "TEAM", v: "Two engineers on backend, data and infrastructure, alongside product and frontend" },
      { k: "USERS", v: "150+ subscribers across the Middle East and Europe, live throughout" },
      { k: "OWNED", v: "Schema and migrations · billing and quotas · media pipeline · admin back office · CI/CD" },
      { k: "NOT MINE", v: "The generation models and the marketing site — our work was the platform underneath" },
      { k: "RUNTIMES", v: "Laravel core, Node/Express services for specific workloads" },
      {
        k: "PRODUCT",
        v: "Free · Pro $12/mo · Business $29/mo, metered at 5 / 10 / 30 AI generations a month",
      },
    ],
    constraints: [
      {
        title: "The product was live the whole time",
        body: "There was never a window to take it down. Every schema change had to be safe against a running application, and every deploy had to be reversible without restoring a backup — which rules out the in-place migration most tutorials show you.",
      },
      {
        title: "Laravel was not up for replacement",
        body: "The core app was Laravel, the team knew Laravel, and a rewrite would have spent a year to arrive back where it started. Anything new had to sit beside it and speak to the same database rather than replace it.",
      },
      {
        title: "A two-person backend team",
        body: "Two of us on the backend, with no platform team and no dedicated ops behind us. That put a hard ceiling on how much machinery the answer could involve: anything we built, we also had to deploy, monitor and be woken up by.",
      },
    ],
    approach:
      "Keep Laravel as the core and give the workloads that were hurting it their own home. Media moves out to object storage so uploads stop occupying request workers; billing and quota state stop being things the application tries to remember. Everything is shaped by one rule: the system has to be changeable while it is running, because it never stops running.",
    decisions: [
      "Designed the schema and a migration strategy so the product could evolve without downtime.",
      "Made Stripe the source of truth for what each tier unlocks — pages, site count, custom domain — rather than mirroring entitlement locally.",
      "Metered AI generations per plan (5 / 10 / 30 a month) with a monthly reset, so a paid capability could not be spent for free.",
      "Built an internal admin panel over the whole tenancy — users, their sites, subscriptions and the companies above them — so support did not mean running SQL against production.",
      "Moved all user media to AWS S3 with signed delivery instead of app-server storage.",
      "Built CI/CD so releases stopped being manual events.",
    ],
    tradeoffs: [
      {
        decision: "Stripe is the source of truth for entitlement",
        instead: "Mirror subscription state into our own tables and trust the local copy",
        cost: "Every entitlement decision is a network call or a cache read, and the cache is another thing that can be wrong.",
        bought: "Three tiers unlock different things — page limits, how many sites, a custom domain, whether the badge shows — and each one is a question asked on nearly every request. Deriving them from Stripe means a lapsed payment cannot leave someone on Business behaviour, a refund takes effect immediately rather than at the next sync, and reconciliation stops being a nightly job that finds yesterday's problems.",
      },
      {
        decision: "Meter generations, not requests",
        instead: "Cap the expensive thing at the API layer, or trust the client not to ask twice",
        cost: "A counter per account per month, with its own reset, and a decision to make every time a generation fails halfway.",
        bought: "The quota sits on the one operation that actually costs money — an AI generation — rather than on traffic, which costs almost nothing. A free account gets five in its first month and a Business account thirty; nobody is rate-limited for browsing their own site, and a failed generation does not silently bill against the allowance.",
      },
      {
        decision: "A Node service for the media pipeline, Laravel for everything else",
        instead: "Handle uploads in Laravel like the rest of the application",
        cost: "A second runtime to deploy, monitor and keep patched — real overhead for a two-person backend team.",
        bought: "An image-heavy profile save stops occupying a PHP-FPM worker that ordinary page requests need. Upload traffic and page traffic stopped competing for the same pool, which is what made the app feel slow under load.",
      },
      {
        decision: "Expand and contract for every schema change",
        instead: "Alter the column and ship it",
        cost: "Three deploys instead of one, and a period where the old and new shapes both exist and both have to be written.",
        bought: "Zero-downtime migrations against live data, and a rollback that is just the previous deploy rather than a restore from backup — which matters more than the extra deploys when the product is earning.",
      },
      {
        decision: "Signed S3 URLs, delivered from the edge",
        instead: "Proxy the bytes through the application server",
        cost: "Expiring URLs to manage, and a signing endpoint that becomes its own hot path.",
        bought: "The application never touches image bytes at all. Delivery is cached at the edge, storage cost is decoupled from server cost, and a profile with twenty photos costs the API exactly as much as one with none.",
      },
    ],
    broke: [
      {
        title: "Entitlement drifted from billing",
        body: "The first version mirrored subscription state locally and trusted it. Stripe webhooks do not arrive in order, do arrive more than once, and occasionally arrive much later than the event they describe — so the local copy and the billing record disagreed, and the disagreement was invisible until a user complained about access they should or should not have had.",
      },
      {
        title: "The fix was to stop remembering",
        body: "Entitlement is now derived from Stripe rather than stored beside it, the webhook handler is idempotent on the event id, and an event carrying a state older than the one already recorded is discarded rather than applied. Replaying the same webhook twice is now a no-op instead of a bug.",
      },
    ],
    diagram: {
      src: "/projects/carder-architecture.svg",
      alt: "Carder architecture: Laravel core with Node services for media, Stripe as the source of truth for entitlement, signed S3 delivery cached at the edge, and an admin back office writing through the same billing paths",
      caption: "* REQUEST, BILLING AND MEDIA PATHS",
    },
    build: [
      {
        title: "Media that never touches the app",
        body: "Every generated site is photo-heavy by nature — a menu, a gallery, a room, a plate. Uploads go straight to S3 behind signed URLs and delivery is cached at the edge, so the application never handles image bytes at all. A site with twenty photos costs the API exactly what an empty one does, which is what let storage grow without the server bill following it.",
        image: img.carderMedia,
        alt: "Photo-heavy generated sites: a photographer's portfolio, a bakery menu and a yoga studio schedule",
      },
      {
        title: "Three tiers, asked on every request",
        body: "Free allows one site and four pages; Pro raises it to ten pages and a chosen address; Business unlocks unlimited pages, three sites, a custom domain and the menu scanner. That is not a badge on an account — it is a question the application asks constantly, on every page save, every publish and every domain lookup. Entitlement is derived from Stripe and cached briefly rather than mirrored, so the answer is never staler than the cache and never wrong after a refund.",
        image: img.carderTiers,
        alt: "Sites of differing scope generated by Carder: a single-page studio site, a multi-page law firm site and a dental clinic site",
      },
      {
        title: "An admin panel over the whole tenancy",
        body: "Every account, every site under it, every subscription and the companies those roll up to, in one back office. It exists because the alternative is support running SQL against production: a plan that needs correcting, a site that has to be suspended, a customer asking what they were charged for. Reading the tenancy is one problem and writing to it is a different one — a change made here moves real money and real published pages, so the panel works through the same billing and entitlement paths the product does rather than writing around them.",
        // No image, deliberately: the admin panel is internal and has no public
        // screen. Drop a redacted screenshot in here if one ever exists.
      },
      {
        title: "Metering the one expensive operation",
        body: "Generation is the only thing in the product that costs real money per use, so the quota lives there and nowhere else: five in a free account's first month, ten a month on Pro, thirty on Business, reset monthly. Sites stay fully editable once the allowance is gone — running out stops you drafting something new, it does not take away what you already made — and a generation that fails partway is not charged against the count.",
        // No image: generation quota is a billing rule, not a screen. The
        // pricing page states the numbers; nothing shows the meter itself.
      },
    ],
    metrics: [
      { value: "150+", caption: "Users, ME & Europe", note: "* two regions, as of Feb 2026" },
      { value: "+40%", caption: "Adoption growth", note: "* after relaunch, to Feb 2026" },
      { value: "3", caption: "Metered tiers", note: "* free · $12 · $29, 5 / 10 / 30 generations" },
      { value: "0", caption: "Downtime migrations", note: "* expand / contract, against live data" },
    ],
    reflection:
      "I’d put the analytics layer in from day one. We shipped adoption features on intuition for the first few months, and the +40% only became legible once instrumentation landed — which means we were probably slower than we needed to be to find it.",
  },
  {
    slug: "golegal",
    name: "Golegal",
    accentWord: "Golegal",
    tagline: "AI Legal Workspace",
    summary:
      "A consumer legal platform where a person with a legal problem drafts the document, gets it reviewed, signs it, tracks what it commits them to, and orders a real solicitor when the AI is not enough. I built five of its modules end to end.",
    role: "Full-Stack & AI Engineer — five modules, end to end",
    timeline: "Dec 2024 – Jan 2026",
    status: "Live",
    liveUrl: "https://go-legal.ai",
    liveLabel: "go-legal.ai",
    stack: ["Nest.js", "Next.js", "PostgreSQL", "OpenAI", "Agentic RAG", "React Flow", "Plate.js"],
    indexMetrics: ["95% accuracy", "-30% manual work", "50+ users"],
    image: img.golegal,
    alt: "The Go Legal AI document editor: a confidentiality agreement open with track changes, beside the Copilot review panel showing traffic-light analysis, a document health score and the individual clause findings behind it",
    problemHeadline: "Generic chat can’t be trusted with legal text",
    problem:
      "Legal teams lose hours to reading, extracting, and reformatting the same document types. Generic LLM chat wasn’t accurate enough to trust with legal text — it hallucinated citations and lost document context.",
    context: [
      {
        k: "OWNED",
        v: "Five modules end to end: document creation and RAG · e-signature and obligation extraction · legal pathways · tasks, calendar and notes · the services marketplace",
      },
      { k: "ALSO BUILT", v: "Payments and the token-metered usage module the paid plans run on" },
      {
        k: "NOT MINE",
        v: "The legal content and the regulated advice — Go Legal Ai is not a law firm, and the services are delivered by independent regulated firms",
      },
      { k: "PRODUCT", v: "Free · Power Up £19/mo · Pro £49/mo, metered in AI credits per action" },
      { k: "REACH", v: "England & Wales for instructed services; document generation across 150+ jurisdictions" },
    ],
    constraints: [
      {
        title: "Plausible is not good enough",
        body: "In most products a wrong AI answer is an annoyance the user corrects. Here the output is a clause someone may sign, so the bar is not fluency — it is whether the thing it asserts is actually true of their document and their jurisdiction. That ruled out the usual answer of a bigger prompt and a better model, and made retrieval quality the whole problem.",
      },
      {
        title: "Every AI action costs real money",
        body: "The expensive operations — drafting, reviewing, extracting — cost per call, and the product sells them as credits. So the cost of a pipeline was never just an infrastructure number to optimise later; it set what a plan could contain and what it had to be priced at. A pipeline that was 30% better and 3x the cost was not an improvement.",
      },
      {
        title: "The legal steps cannot be skipped, only made lighter",
        body: "Drafting, reviewing, signing and tracking obligations are a sequence with real dependencies, and none of them can be removed to make the flow shorter. Whatever was done for the experience had to come out of how the steps are presented, not out of the steps themselves.",
      },
    ],
    approach:
      "The fix wasn’t a better prompt. It was retrieval that preserves legal structure, and agents that know which extraction path a document belongs to. Around that sits the part that makes it a product rather than a demo: metering the expensive operations honestly, and collapsing a multi-step legal flow into something a non-lawyer will actually finish.",
    tradeoffs: [
      {
        decision: "Sell AI work as credits, priced per action",
        instead: "One flat unlimited subscription, the way most SaaS is sold",
        cost: "Credits are a concept the customer has to learn, and every plan page has to explain them. It is a worse pitch than the word unlimited.",
        bought: "The price/token ratio can be tuned until it works at both ends: heavy users cannot make a plan unprofitable, and light users are not quietly subsidising them. It also means an expensive new capability can ship at a fair price instead of being priced for the worst-case user or not shipping at all.",
      },
      {
        decision: "Tune retrieval for precision, not coverage",
        instead: "Retrieve generously and let the model decide what is relevant",
        cost: "More work in chunking and routing, and an occasional relevant passage that does not surface.",
        bought: "Far fewer confident wrong answers. On legal text a passage retrieved without its context can be quoted accurately and still be misleading, and that failure is much more expensive than a miss the user can see.",
      },
      {
        decision: "One working surface for drafting, review and signing",
        instead: "A wizard with a page per step, which is easier to build and easier to reason about",
        cost: "A single screen carrying much more state, and a harder component to keep coherent as the feature set grows.",
        bought: "The user stays in their document. Every hop between pages in a legal flow is somewhere to abandon it, and the whole product depends on people finishing.",
      },
    ],
    decisions: [
      "Built an agentic RAG pipeline over PostgreSQL with vector retrieval.",
      "Chunked and embedded documents with structure preserved, so clause context survives retrieval.",
      "Used agent workflows to route document types to the right extraction path.",
      "Shipped a React Flow visual workflow builder so non-engineers can compose pipelines.",
      "Used Plate.js for the in-app document editor, with extraction results written inline.",
    ],
    diagram: {
      src: "/projects/golegal-rag.svg",
      alt: "Golegal agentic RAG pipeline: documents chunked along their own clause hierarchy so each chunk keeps its ancestry, embedded into PostgreSQL, retrieved with that context intact, then routed by a classifier to a per-document-type agent with its own tools and validation schema",
      caption: "* RETRIEVAL THAT KEEPS THE DOCUMENT SHAPE",
    },
    build: [
      {
        title: "Structure-preserving retrieval",
        body: "Chunking follows the document’s own hierarchy — sections, clauses, sub-clauses — and every chunk carries its ancestry. A retrieved clause arrives with the context that makes it mean something, which is what killed the hallucinated citations.",
        image: img.golegal,
        alt: "Document retrieval view in Golegal",
      },
      {
        title: "Agent routing by document type",
        body: "A classifier routes each upload to a dedicated extraction agent. Contracts, filings, and correspondence each get their own tool set and validation schema rather than one prompt trying to cover everything.",
        image: img.diagram,
        alt: "Agent routing diagram",
      },
      {
        title: "Legal pathways, as a graph you can see",
        body: "A legal problem is a sequence, not a document: send the letter, wait the statutory period, file the form, instruct someone if it does not land. Pathways models that as a React Flow canvas where each node is a real thing the platform can do — draft from a smart template, run an AI step, order a service like asset tracing, produce a court form — and the edges are what has to happen first. The user watches their own case advance through it, step three of six, instead of being handed a checklist and left to it.",
        image: "/projects/golegal-pathways.png",
        alt: "The Legal Pathway builder: a React Flow canvas with a Start node branching into an action, a smart template, an asset-tracing service, an AI step and a court form, connected by dependency edges",
      },
      {
        title: "Signature, and what the signature commits you to",
        body: "Multi-party signing with a certificate and an audit trail is the table-stakes half. The half worth building was what happens after: the platform reads the executed document and extracts its obligations and their dates — notice periods, renewal windows, payment deadlines — then puts them somewhere they will be seen again. A signed contract is a set of future commitments, and the usual failure is not disputing them, it is forgetting one.",
        image: "/projects/golegal-signature.png",
        alt: "A fully signed document in Go Legal AI showing both signers with timestamps, alongside the Extract obligations action and the signing certificate",
      },
      {
        title: "The deadlines the documents created",
        body: "Extracted obligations land in a calendar with tasks, notes and reminders around them, so the date a document created is tracked in the same place as the work it implies. The dashboard leads with what is overdue and what is coming, because for a person handling their own legal matter the expensive mistake is almost never the drafting — it is missing the date.",
        image: "/projects/golegal-tasks.png",
        alt: "The Tasks and Deadlines module: a calendar view with counters for upcoming deadlines, pending and overdue tasks, and reminders, plus notes and integrations tabs",
      },
      {
        title: "When the AI is not enough, order a person",
        body: "Some problems need a regulated solicitor, and pretending otherwise is how legal tech gets people into trouble. The services module is a priced catalogue of real work — a lawyer checking your AI draft, a contract review with tracked mark-up, a letter before action, a statutory demand drafted and served — ordered and paid for in the platform, with the fee credited against the first instruction. Every price carries VAT, jurisdiction is stated up front, and the page says plainly that Go Legal AI is not a law firm.",
        image: "/projects/golegal-services.png",
        alt: "The Legal Services catalogue: fifteen priced services across consultation, contracts, disputes, document services, intellectual property, investigations and property, each with a fixed fee plus VAT",
      },
    ],
    metrics: [
      { value: "95%", caption: "Extraction accuracy", note: "* on the evaluated set, Jan 2026" },
      { value: "100+", caption: "Files / month", note: "* in production, at handover" },
      { value: "-30%", caption: "Manual document work", note: "* reported by users, Jan 2026" },
      { value: "50+", caption: "Active users", note: "* legal professionals, Jan 2026" },
    ],
    reflection:
      "I’d build the evaluation harness before the pipeline, not alongside it. We tuned chunking by feel for too long, and every change felt like a coin flip until there was a scored regression set to argue with.",
  },
  {
    slug: "muterpe",
    name: "Muterpe",
    accentWord: "Muterpe",
    tagline: "AI Image Generation SaaS",
    summary: "An AI model-training and image-generation platform, built from the ground up and monetized.",
    role: "Founding Engineer",
    timeline: "2023 – Present",
    status: "Live, monetized",
    stack: ["Next.js", "React", "PostgreSQL", "OpenAI", "Fal.ai", "AWS S3"],
    indexMetrics: ["200+ users", "$5K+ revenue", "99% uptime"],
    image: img.muterpe,
    alt: "Muterpe AI image generation interface with result grid",
    problemHeadline: "Generic models don’t hold a likeness",
    problem:
      "Generic image generators don’t hold a brand or a person’s likeness. Muterpe needed per-user model training, plus a generation pipeline fast enough that users wouldn’t abandon mid-flow.",
    approach:
      "Training is slow and generation must feel instant, so the architecture is built around never letting one block the other.",
    decisions: [
      "Built the model-training and generation pipeline on Fal.ai with OpenAI in the loop for prompt shaping.",
      "Used an async job queue so training and generation never block the UI.",
      "Stored and delivered every asset from S3 rather than the application server.",
      "Wired usage-based monetization directly into the generation flow.",
    ],
    diagram: {
      src: "/projects/muterpe-pipeline.svg",
      alt: "Muterpe train and generate pipeline: an upload enqueues a per-user training job on Fal.ai while the interface stays responsive, and generation shapes the prompt through OpenAI, streams results as they land, meters usage for billing and serves every asset from S3",
      caption: "* TRAIN / GENERATE PIPELINE",
    },
    build: [
      {
        title: "Per-user model training",
        body: "Users upload a set, the job queue picks it up, and training progress streams back to the UI. Nothing about the app is blocked while a model bakes.",
        image: img.muterpe,
        alt: "Muterpe model training screen",
      },
      {
        title: "Generation that feels immediate",
        body: "Prompts are shaped server-side before they hit the generation provider, and results stream in as they land. Perceived speed improved ~40% without changing the underlying model.",
        image: img.terminal,
        alt: "Generation job logs",
      },
    ],
    metrics: [
      { value: "200+", caption: "Users", note: "* self-serve signup" },
      { value: "$5K+", caption: "Revenue", note: "* usage-based" },
      { value: "99%", caption: "Uptime", note: "* rolling 12 months" },
      // Keeps the two qualifiers the write-up above states: it is perceived
      // speed, from streaming, and it is approximate. "Faster generation" flat
      // was a different and larger claim than the one that was measured.
      { value: "~40%", caption: "Faster, perceived", note: "* streaming, vs. first release" },
    ],
    reflection:
      "Usage-based billing went in late, and retrofitting metering onto a pipeline that was already running cost more than building it in from the start would have. I’d meter first and price second next time.",
  },
  {
    slug: "volumize",
    name: "Volumize",
    accentWord: "Volumize",
    tagline: "Telehealth E-Commerce Platform",
    summary:
      "A telehealth commerce platform for hair-loss treatment — medical intake, doctor approval, prescriptions, payments, despatch, and subscriptions in one lifecycle across two apps.",
    role: "Full-Stack Engineer",
    timeline: "Feb 2026 – Present",
    status: "Live",
    liveUrl: "https://volumize.co.uk",
    liveLabel: "volumize.co.uk",
    stack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "MongoDB",
      "Mongoose",
      "Socket.IO",
      "Stripe",
      "Royal Mail API",
      "AWS S3",
      "Turborepo",
      "RAG",
      "LLM",
      "Sentry",
    ],
    /*
     * Outcomes, not repository statistics. This used to lead with route-file
     * counts and a dependency-audit score — true, but they describe the shape
     * of the codebase rather than anything the business got. These are what the
     * platform actually changed once it was running.
     */
    indexMetrics: ["250+ subscriptions", "£31K+ revenue", "4 back-office roles"],
    image: img.volumize,
    alt: "Volumize telehealth commerce dashboard",
    problemHeadline: "Intake and checkout live in different systems",
    problem:
      "A hair-loss treatment journey usually runs across disconnected tools. Medical intake sits apart from the purchase flow, clinical approval and prescription handoff are manual, and order, subscription, and refund operations are scattered — which makes payments hard to reconcile and leaves nobody with a view of the whole journey.",
    context: [
      {
        k: "OWNED",
        v: "The lifecycle end to end: intake and the RAG recommendation, checkout and subscriptions, despatch, the role-based back office, monitoring and the content admin",
      },
      { k: "ROLES", v: "Four in one back office — admin · pharmacist · doctor · marketing" },
      {
        k: "NOT MINE",
        v: "The clinical decision and the dispensing — prescribing is done by the clinicians, fulfilment by a GPhC-registered pharmacy",
      },
      { k: "PRODUCT", v: "£19/mo base on 3- and 6-month courses, despatched a cycle ahead" },
      { k: "SURFACES", v: "A customer app and an operational back office over three shared packages" },
    ],
    constraints: [
      {
        title: "A missed dose is the failure that matters",
        body: "This is a treatment where stopping regresses the result — the FAQ says so in the company's own words. So the thing the system absolutely cannot do is let a subscriber run out between cycles. That single requirement drove more of the architecture than the commerce did: it is why despatch runs early, why retries exist, and why the order state machine refuses to go backwards.",
      },
      {
        title: "The AI cannot be the prescriber",
        body: "A model reading a medical questionnaire and recommending a treatment is useful. A model issuing a prescription is a regulated act it is not allowed to perform. Every design here had to keep a clinician in the path without making them a bottleneck who reads raw form answers cold.",
      },
      {
        title: "Enough users that failures are not theoretical",
        body: "At this volume something is always mid-flight — an approval, a despatch, a renewal. A quiet outage is not an inconvenience; it is a batch of people whose medication does not ship. The system had to tell us it was breaking before a customer did.",
      },
    ],
    approach:
      "Put the whole lifecycle behind one architecture: a Turborepo monorepo with a customer app and an operational back office, sharing auth, data models, and UI so the two surfaces cannot drift apart. Then design the subscription around continuity rather than around the billing date, because on a course of treatment the calendar the customer cares about is when the medicine runs out.",
    tradeoffs: [
      {
        decision: "Despatch the next cycle two weeks before the current one runs out",
        instead: "Ship on the renewal date, the way a subscription normally works",
        cost: "Stock is in flight earlier and there is more of it out at any moment, and a cancellation mid-cycle can land after a despatch has already gone.",
        bought: "Nobody misses a dose. On a treatment whose benefits regress once it stops, a two-day gap in the post is not a logistics inconvenience — it is the customer losing the result they are paying for, and then leaving. Shipping early converts a delivery risk into a small inventory cost.",
      },
      {
        decision: "Retry despatch repeatedly rather than failing to a human",
        instead: "Fail the job on the first error and raise it for someone to handle",
        cost: "Retries have to be idempotent or they duplicate an order, which is a real cost in physical goods rather than a duplicated row.",
        bought: "A transient Royal Mail or pharmacy error stops being a missed delivery. Most of these failures resolve on their own within minutes; escalating each one to a person is how a queue becomes a backlog overnight.",
      },
      {
        decision: "The questionnaire recommends, a clinician decides",
        instead: "Let the pipeline issue the plan directly for a doctor to rubber-stamp",
        cost: "Throughput is bounded by clinician time, and the AI's work is advisory rather than final.",
        bought: "It is lawful, and it is safe. The prescriber sees a suggested plan with its reasoning instead of raw form answers, which is what actually made review faster — the speed came from better input to the human, not from removing them.",
      },
      {
        decision: "Health-check services and error tracking from the start",
        instead: "Rely on customer reports and server logs, which is free",
        cost: "More services to run, and alert thresholds that need tuning or they train you to ignore them.",
        bought: "We hear about an outage before a patient does. In a business that ships medicine on a schedule, the gap between something breaking and someone noticing is measured in missed deliveries.",
      },
    ],
    decisions: [
      "Split the product into a customer app and an admin app over three shared packages — auth, db, ui — so session logic and domain models have exactly one definition.",
      "Issued separate session tokens for users and admins rather than one shared trust boundary, keeping role-scoped checks simple and the blast radius small.",
      "Modelled the order lifecycle as explicit statuses and transitions, connecting questionnaire, doctor review, prescription generation, and fulfilment into one traceable pipeline.",
      "Kept refunds executing against the same Stripe environment as the original transaction, so payment operations reconcile instead of drifting.",
      "Made product pages config-driven, so merchandising changes are composition rather than layout rewrites.",
      "Ran the medical questionnaire through a retrieval-augmented pipeline over the treatment material, so intake returns a suggested plan with its reasoning for a clinician to accept or override — never an automatic prescription.",
      "Enforced role-based access server-side for admin, pharmacist, doctor and marketing, so a marketing login cannot reach patient answers by knowing a URL.",
      "Put the blog and campaign content in the same admin, so marketing ships copy without a deploy.",
      "Wired Socket.IO for event-driven status updates, giving doctors and admins live operational visibility.",
      "Scheduled the next cycle to despatch two weeks before the current course runs out, with retries, so a subscriber never waits on the post to take a dose.",
      "Ran health checks across the services and wired Sentry, so an outage reaches us before it reaches a patient.",
      "Integrated the Royal Mail API so despatch generates labels and syncs tracking back onto the order, taking approved prescriptions to shipped without manual handling.",
    ],
    diagram: {
      src: "/projects/volumize-lifecycle.svg",
      alt: "Volumize order lifecycle: signup, medical questionnaire and checkout, then doctor review branching to either prescription, pharmacy handoff and Royal Mail despatch feeding subscription renewal, or rejection and refund",
      caption: "* ONE ORDER, END TO END",
    },
    build: [
      {
        title: "Two apps, one domain layer",
        body: "The customer app and the back office are separate deployments over shared auth, database, and UI packages. Fifteen Mongoose models live in one place, so an order means the same thing on both sides of the platform.",
        image: img.volumize,
        alt: "Volumize monorepo structure",
      },
      {
        title: "Intake to delivery, as one pipeline",
        body: "Signup leads into a medical questionnaire, then checkout, then doctor review. Approval generates a prescription PDF and hands off to the pharmacy; rejection stops the order. Despatch runs through the Royal Mail API — labels generated and tracking written straight back onto the order — so nobody is creating labels by hand. Delivery rolls into the subscription renewal cycle, and refunds are a modelled branch rather than an afterthought.",
        image: img.diagram,
        alt: "Treatment and commerce lifecycle flow",
      },
      {
        title: "A questionnaire that recommends, not just records",
        body: "The medical intake is not a form that files answers away for a doctor to read cold. Answers go through a retrieval-augmented pipeline over the treatment material — the ingredients, their indications, the contraindications — and it comes back with a suggested plan and the reasoning for it. That suggestion is a starting point for the clinician, never a decision: the prescriber still reviews and still approves, because a model that recommends a prescription without a human in the path is a regulatory problem, not a feature.",
      },
      {
        title: "Four roles, one back office",
        body: "Admin, pharmacist, doctor and marketing all work in the same operational app and must not see the same thing. A doctor needs the clinical questionnaire and the approval decision; a pharmacist needs the approved prescription and the despatch queue; marketing needs the content and the campaign surfaces and no patient data at all. Role-based access is enforced on the server per route rather than by hiding buttons, because in a system carrying medical answers and prescriptions the interface is not the security boundary.",
      },
      {
        title: "Content the marketing team owns",
        body: "The blog and its posts are managed from the same admin, so campaign content ships without a deploy and without an engineer. It is the least clinically interesting part of the platform and one of the most requested: the alternative is a marketing team filing tickets to change a paragraph.",
      },
      {
        title: "Security hardening pass",
        body: "A phased dependency remediation — non-breaking fixes first, breaking upgrades second — prioritising routing, middleware, email transport, and the parsing and network stack. Next.js moved to 16.3.0 and Nodemailer to 9.0.4, clearing every high and moderate finding across a 1,127-package graph. Query optimisation and edge caching took 1.8s off page load and 35% off API response time in the same pass.",
        image: img.terminal,
        alt: "Dependency audit output",
      },
    ],
    metrics: [
      /*
       * Revenue first, then the two operational numbers that produced it. The
       * build statistics that used to sit here — 94 route files, a 97% cut in
       * vulnerabilities, an audit score of 99 — are still true and still
       * described in the build blocks above; they are just not what a clinic
       * or a client is asking about. The saved admin hours and the page-load
       * improvement moved into those blocks for the same reason.
       */
      {
        value: "250+",
        caption: "Live subscriptions",
        note: "* £19/mo base, 3- and 6-month plans",
      },
      { value: "£31K+", caption: "Subscription revenue", note: "* booked across those plans" },
      {
        value: "-45%",
        caption: "Approval turnaround",
        note: "* review to prescription, vs. manual handoff",
      },
      {
        value: "-85%",
        caption: "Order despatch time",
        note: "* after Royal Mail label + tracking sync",
      },
      { value: "4", caption: "Back-office roles", note: "* admin · pharmacist · doctor · marketing" },
    ],
    reflection:
      "The security work was reactive — 34 findings had already accumulated before anyone went looking. The fix was a one-off cycle when it should have been a gate: audit thresholds in CI, so the graph never drifts that far again. Cutting vulnerabilities by 97% reads well, but not having needed to reads better.",
  },
  {
    slug: "wisdomup",
    name: "WisdomUp",
    accentWord: "WisdomUp",
    tagline: "Multi-Service E-Commerce Platform",
    summary:
      "A three-service commerce platform — storefront, transactional API, and CMS admin — built around checkout that survives its own edge cases.",
    role: "Full-Stack Product Engineer",
    timeline: "2026 – Present",
    status: "In development",
    inDevelopment: true,
    stack: [
      "Next.js",
      "TypeScript",
      "Express 5",
      "MongoDB",
      "Payload CMS",
      "Stripe",
      "Redux Toolkit",
      "RTK Query",
      "Zod",
    ],
    indexMetrics: ["3 services", "8-layer payment guard", "14 settlement tests"],
    image: img.wisdomup,
    alt: "WisdomUp storefront and admin dashboard",
    problemHeadline: "Checkout breaks in the edge cases",
    problem:
      "E-commerce builds tend to fail in the same three places. Content changes need a developer, so campaigns wait on deploys. Payment edge cases — duplicate webhooks, events arriving out of order, amounts that do not match — turn into real financial risk. And a monolith makes both problems harder to fix safely.",
    approach:
      "Separate the three concerns into independently deployable services, then treat settlement as a distributed-systems problem rather than a happy path: assume events arrive twice, late, or out of order, and make the order state machine refuse to go backwards.",
    decisions: [
      "Split into a storefront, an Express transactional API, and a Payload CMS admin, each deployable on its own with bounded ownership over a shared database.",
      "Settled payments down two paths — immediate confirmation after client success, plus a webhook fallback — so a dropped browser never loses an order.",
      "Guarded settlement with signature verification, ownership and amount checks, idempotency keys, unique transaction indexing, and replay protection.",
      "Enforced monotonic order status, so a stale webhook cannot regress an order that has already moved on.",
      "Derived catalog scope from host and market, enforced again at checkout, so local and global products cannot cross storefronts.",
      "Drove homepage sections, navigation, FAQs, and testimonials from the CMS with typed contracts and defensive rendering, so a missing field degrades instead of breaking the page.",
    ],
    diagram: {
      src: "/projects/wisdomup-settlement.svg",
      alt: "WisdomUp architecture: a storefront, an Express transactional API and a Payload CMS admin over one shared database, with payment settled down two independent paths behind eight guard layers and an order status that only moves forward",
      caption: "* THREE SERVICES + DUAL SETTLEMENT",
    },
    build: [
      {
        title: "Two paths to settled",
        body: "The client confirms with Stripe and the backend records it immediately. The webhook then arrives and reconciles — verifying signature, checking the amount and owner, deduplicating on a unique transaction index, and refusing any event that would move the order backwards. Fourteen tests cover that logic specifically.",
        image: img.wisdomup,
        alt: "Checkout and settlement flow",
      },
      {
        title: "Merchandising without a deploy",
        body: "Hero, banners, feature bars, FAQs, and testimonials are CMS collections, not components. Eleven admin collections plus site settings and navigation as editable globals mean a campaign change is an edit, not a release — with CSV product import for bulk catalog work.",
        image: img.diagram,
        alt: "Payload CMS collections and globals",
      },
      {
        title: "Storefront surface",
        body: "Listing and detail flows with category filtering and search, cart and wishlist, guest checkout with resumable session state, promo codes validated server-side for eligibility and discount, and reviews rendered moderation-aware. Fifty components across twenty-three route directories.",
        image: img.terminal,
        alt: "Storefront routes and components",
      },
    ],
    metrics: [
      { value: "3", caption: "Deployable services", note: "* storefront · API · CMS" },
      { value: "8", caption: "Payment guard layers", note: "* signature to state machine" },
      { value: "14", caption: "Settlement tests passing", note: "* confirmation logic" },
      { value: "39", caption: "Backend route handlers", note: "* across 10 route files" },
    ],
    reflection:
      "Everything measurable here is about the build, not the business. The payment layer is hardened and tested, but checkout success rate, reconciliation accuracy, and promo conversion are still targets rather than readings — I set them without shipping the instrumentation to answer them. Reliability engineering you cannot observe in production is a hypothesis, and I would wire the funnel telemetry before adding another feature.",
  },
  {
    slug: "alfa",
    name: "Alfa",
    accentWord: "Alfa",
    tagline: "Multi-Role Fintech Platform",
    summary:
      "A role-aware fintech platform serving personal, business, and admin journeys from one architecture — onboarding, transfers, bill splitting, top-ups, currency conversion, scheduled payments, and card management over Python microservices.",
    role: "Full-Stack Engineer — Python microservices & Next.js client",
    timeline: "Feb 2026 – Present",
    status: "In development",
    inDevelopment: true,
    stack: [
      "Python",
      "FastAPI",
      "Supabase",
      "GraphQL",
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Redux Toolkit",
      "RTK Query",
      "Zod",
      "Tailwind v4",
      "AWS S3",
    ],
    /*
     * Services delivered and interfaces designed, rather than the shape of the
     * repository. "4 route groups" described a directory layout; these describe
     * what the platform does and what was built to make it do it.
     */
    indexMetrics: ["1 request per screen", "auth resolved once, not per page", "0 cross-service outages"],
    image: img.alfa,
    alt: "Alfa fintech dashboard",
    problemHeadline: "Three roles, one routing surface",
    problem:
      "Fintech products tend to break down exactly where account setup and role switching meet. A user can hold both a personal and a business account with no session chosen yet, or be mid-onboarding — and every page that guesses at that state becomes another place for the routing to go wrong.",
    approach:
      "Two halves, each with one rule. On the server, every financial capability is its own FastAPI service behind a GraphQL layer, so a change to currency conversion cannot take transfers down with it. On the client, the auth decision splits in two: middleware does one cheap thing at the edge — check a token exists — and everything conditional (role, session, onboarding completeness) resolves against a single bootstrapped user object, so the rules live in one guard instead of scattered across pages.",
    decisions: [
      "Built each financial capability as its own FastAPI service — transfers, bill splitting, top-ups, currency conversion, recurring payments — rather than one monolith where an incident anywhere is an incident everywhere.",
      "Put 10+ GraphQL APIs in front of those services, so the client asks for what a screen needs in one request instead of stitching together REST calls per role.",
      "Used Supabase for auth and persistence, keeping row-level rules next to the data rather than re-implemented in every service.",
      "Kept middleware to a token-presence gate; role and session rules run in a RequireAuth guard against Redux state.",
      "Bootstrapped the session once from /auth/user/me into a userSlice, making it the single source of truth for the app.",
      "Used one RTK Query baseApi with domain endpoints injected per feature, so seven API areas share one reducer, one middleware, and one cache.",
      "Routed onboarding by account type, letting the guard redirect incomplete journeys instead of each page checking for itself.",
      "Handled S3 document upload and delete inside Next.js route handlers with AWS SDK v3, keeping credentials server-side.",
      "Validated forms with Zod schemas shared between onboarding and dashboard flows.",
    ],
    diagram: {
      src: "/projects/alfa-services.svg",
      alt: "Alfa architecture: an edge token gate and a single client-side guard resolve role and session once per visit, one RTK Query base API serves seven domains, and 10+ GraphQL APIs sit in front of six independently deployable FastAPI services over Supabase",
      caption: "* AUTH + SERVICE TOPOLOGY",
    },
    build: [
      {
        title: "Hybrid auth model",
        body: "Login optionally passes through 2FA before an access token lands in a cookie. A bootstrap provider then fetches the user once and hands Redux the session. From there the guard resolves one of four outcomes — admin area, dashboard, onboarding, or an account selector when someone holds both account types and has not picked a session.",
        image: img.alfa,
        alt: "Alfa authentication and session flow",
      },
      {
        title: "One API, seven domains",
        body: "Rather than a slice per feature, a single baseApi is created once and each domain injects its own endpoints: auth, business, cards, transactions, schedules, wallet, admin. Adding an endpoint means touching one file and getting caching, tag invalidation, and generated hooks for free.",
        image: img.diagram,
        alt: "RTK Query base API with injected domain endpoints",
      },
      {
        title: "Four route groups, one set of rules",
        body: "The app is partitioned by what a person is allowed to be doing rather than by feature: auth, onboarding, dashboard and admin. Onboarding is routed by account type, so an incomplete business journey and an incomplete personal one are different paths through the same group rather than the same page branching internally. Zod schemas are shared between onboarding and the dashboard, which means a field validated at signup is validated identically when it is edited a year later — the usual failure being two definitions of the same rule that drift.",
      },
      {
        title: "Money movement surfaces",
        body: "Transfers for personal and business contexts, payment requests, calendar-driven scheduled payments, transaction history, and card issuing and assignment — each built from shared layout shells and form primitives so a new dashboard screen starts from composition rather than scratch.",
        image: img.terminal,
        alt: "Alfa dashboard modules",
      },
    ],
    metrics: [
      /*
       * Efficiency and failure containment, not counts of what was integrated.
       * Each of these is a comparison against the way it would otherwise work —
       * one round trip instead of several, one auth resolution instead of one
       * per page, one failing capability instead of all of them. There is no
       * latency or conversion figure here because the platform has not been in
       * front of enough customers to have measured one, and the last tile says
       * so rather than implying otherwise.
       */
      {
        value: "1",
        caption: "Request per screen",
        note: "* one GraphQL call, not a REST fan-out per role",
      },
      {
        value: "1x",
        caption: "Auth resolved per session",
        note: "* bootstrapped once, instead of re-derived on every page",
      },
      {
        value: "0",
        caption: "Cross-service outages possible",
        note: "* currency conversion failing cannot stop transfers",
      },
      { value: "WIP", caption: "In active development", note: "* not a finished claim" },
    ],
    reflection:
      "The architecture is sound but under-tested for what it is. Money movement and auth are exactly the paths that deserve integration and end-to-end coverage, and right now correctness rests on the guard logic being right rather than on anything proving it. That is the next thing I would build, before analytics on onboarding drop-off or feature flags for staged rollout.",
  }
];

/**
 * Reading order, and the numbering that comes with it.
 *
 * The case-study page shows two numerals for the same project: a position
 * counter in the sticky bar ([02 / 06]) and the authored [CASE STUDY nn] tag.
 * Those were separate values — declaration order for one, a hand-written
 * `index` field for the other — and four of the six disagreed. Deriving the
 * index from this list makes them the same number by construction, and makes
 * prev/next walk the projects in the order the site actually presents them.
 */
const ORDER = ["carder", "volumize", "golegal", "alfa", "wisdomup", "muterpe"] as const;

export const projects: Project[] = ORDER.map((slug, i) => {
  const project = authored.find((p) => p.slug === slug);
  if (!project) throw new Error(`ORDER lists a slug with no project: ${slug}`);
  return { ...project, index: String(i + 1).padStart(2, "0") };
});

/*
 * The guard above catches a slug with no project. This catches the direction
 * that fails quietly: a project added to `authored` and forgotten here would
 * simply vanish — no route from generateStaticParams, no card on the index, no
 * entry in the sitemap, and nothing anywhere to say so.
 */
if (projects.length !== authored.length) {
  const missing = authored.map((p) => p.slug).filter((slug) => !ORDER.includes(slug as never));
  throw new Error(`Projects missing from ORDER: ${missing.join(", ")}`);
}

const bySlug = Object.fromEntries(projects.map((p) => [p.slug, p])) as Record<string, Project>;

/**
 * The four the index leads with, in the order it leads with them.
 *
 * `ORDER` above is *routing* order — it feeds `generateStaticParams`, the
 * case-study numbering and prev/next, so it stays put. This is
 * presentation order, and the two are allowed to differ: WisdomUp and Muterpe
 * still have full case studies, they just no longer earn a pinned card on the
 * index. They surface through `otherWork` instead, which links straight at
 * those same pages.
 */
export const featuredProjects: Project[] = ["carder", "volumize", "golegal", "alfa"].map(
  (slug) => bySlug[slug],
);

export type OtherWork = {
  name: string;
  tagline: string;
  /** One line. This list is an index, not a second case-study section. */
  note: string;
  stack: string[];
  status: string;
  href: string;
  /** Case studies link inward; everything else opens in a new tab. */
  external?: boolean;
  hrefLabel: string;
};

/**
 * Shipped work that isn't the argument the index is making. Two of these have
 * full case studies and point at them; the third is a live site and points at
 * itself.
 */
export const otherWork: OtherWork[] = [
  {
    name: "WisdomUp",
    tagline: "Multi-Service E-Commerce Platform",
    note: "Storefront, transactional API, and CMS admin as three deployable services, with settlement guarded down two paths so a dropped browser never loses an order.",
    stack: ["Next.js", "Express 5", "MongoDB", "Payload CMS", "Stripe"],
    status: "In development",
    href: "/work/wisdomup",
    hrefLabel: "Read the case study",
  },
  {
    name: "LightspeedGo",
    tagline: "Logistics & Delivery Platform",
    note: "Marketing and booking surface for a courier operation — live, and the front door for the dispatch flow behind it.",
    stack: ["Next.js", "TypeScript", "Tailwind"],
    status: "Live",
    href: "https://lightspeedgo.com",
    external: true,
    hrefLabel: "lightspeedgo.com",
  },
  {
    name: "Muterpe",
    tagline: "AI Image Generation SaaS",
    note: "Per-user model training and generation on Fal.ai, monetized usage-based, with an async queue so a baking model never blocks the UI.",
    stack: ["Next.js", "PostgreSQL", "Fal.ai", "OpenAI", "AWS S3"],
    status: "Live, monetized",
    href: "/work/muterpe",
    hrefLabel: "Read the case study",
  },
];

/** One node of the agent's state machine, as the index replays it. */
export type TraceStep = {
  id: string;
  label: string;
  /** What the node actually emitted — shown as the span's result line. */
  detail: string;
  ms: number;
  tokens?: number;
  /** The human-approval interrupt. The replay stops here until someone taps. */
  gate?: boolean;
};

/**
 * mailagent — in build, not shipped, and listed that way on purpose.
 *
 * The interesting claim here isn't "an LLM reads your email", it's the
 * engineering around it: a scoring harness that existed before the extractor,
 * a retrieval comparison whose losing arm shipped disabled, and cost accounting
 * that records an unpriced call as NULL rather than lying with a zero. The
 * index replays the graph instead of describing it.
 */
export const comingSoon = {
  name: "mailagent",
  tagline: "Human-in-the-Loop Scheduling Agent",
  status: "In build",
  summary:
    "Reads Gmail, spots meeting requests, extracts the details, checks the calendar for conflicts, and sends a Telegram card with Confirm / Edit / Cancel. Nothing touches the calendar without a human tap.",
  stack: [
    "Python 3.12",
    "FastAPI",
    "LangGraph",
    "Gemini",
    "Postgres + pgvector",
    "Gmail & Calendar APIs",
    "Telegram Bot API",
    "Next.js",
  ],
  trace: [
    {
      id: "classify",
      label: "classify",
      detail: 'intent="schedule_meeting" · confidence 0.94',
      ms: 412,
      tokens: 318,
    },
    {
      id: "extract",
      label: "extract",
      detail: 'title="Design sync" · Thu 14:00–14:45 GMT · 3 attendees',
      ms: 1180,
      tokens: 902,
    },
    {
      id: "retrieve",
      label: "retrieve",
      detail: "pgvector · 5 prior threads · hit@5 1.00 (fusion off)",
      ms: 96,
    },
    {
      id: "conflict_check",
      label: "conflict_check",
      detail: "1 overlap — “1:1 · Ali” Thu 14:30. Proposing 15:00.",
      ms: 240,
    },
    {
      id: "human_approval",
      label: "human_approval",
      detail: "interrupt — awaiting Telegram callback",
      ms: 0,
      gate: true,
    },
    {
      id: "act",
      label: "act",
      detail: "calendar.events.insert · 200 · reply drafted",
      ms: 588,
    },
  ] satisfies TraceStep[],
  /** Numbers that came out of the harness, not out of a pitch. */
  evidence: [
    { value: "92.9%", caption: "Exact-match extraction", note: "* 14 hand-labelled fixtures" },
    { value: "100%", caption: "Retrieval hit@5", note: "* vector-only, 29 queries" },
    { value: "NULL", caption: "Unpriced call cost", note: "* never recorded as 0" },
    { value: "OFF", caption: "RRF fusion, shipped", note: "* built, measured, lost" },
  ],
  /**
   * The most distinctive part of the write-up. Four real production bugs, kept
   * in the reader's view rather than buried in a repo — a portfolio that only
   * lists wins is a portfolio nobody believes.
   */
  broke: [
    {
      title: "Auth bypass",
      body: "An empty Telegram secret matched an empty header, so an unsigned request authenticated cleanly. Fixed by refusing to start when the secret is unset.",
    },
    {
      title: "Silent batch collapse",
      body: "The Gemini SDK quietly folded an embedding batch, returning fewer vectors than inputs with no error. Caught by a length assertion that should have been there first.",
    },
    {
      title: "tsquery AND vs OR",
      body: "A Postgres full-text query built with the wrong operator flipped a benchmark result. The BM25 arm looked worse than it was for two days.",
    },
    {
      title: "A confident wrong answer",
      body: "An A/B run picked a winner on one pass. Repeating it exposed fixture-level variance wide enough to swallow the difference — the result was noise wearing a decision.",
    },
  ],
} as const;

export const getProject = (slug?: string) => projects.find((p) => p.slug === slug);

export const projectNeighbours = (slug: string) => {
  const i = projects.findIndex((p) => p.slug === slug);
  if (i < 0) return { prev: undefined, next: undefined, position: 0 };
  return {
    prev: projects[(i - 1 + projects.length) % projects.length],
    next: projects[(i + 1) % projects.length],
    position: i + 1,
  };
};
